//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSE.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHSE.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcreEditor=Acre Editor
        ///ActivityEditor=Record Editor
        ///BuildingEditor=Building Editor
        ///FieldItemEditor=Field Item Editor
        ///FlagEditor=Flag Editor
        ///ItemReceivedEditor=Received Item List Editor
        ///SimpleHexEditor=RAM Edit
        ///SysBotRAMEdit=SysBotUI
        ///SysBotUI=SysBotUI
        ///TerrainEditor=Terrain Editor
        ///AcreEditor.B_Cancel=Cancel
        ///AcreEditor.B_Export=Export
        ///AcreEditor.B_Import=Import
        ///AcreEditor.B_Save=Save
        ///AcreEditor.L_AcreList=Name Table:
        ///AcreEditor.L_Hovered=Hovered
        ///AcreEditor.L_X0=x
        ///AcreEditor.L_X1=1
        ///AcreEditor. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcreEditor=Acre Editor
        ///ActivityEditor=Record Editor
        ///BuildingEditor=Building Editor
        ///FieldItemEditor=Field Item Editor
        ///FlagEditor=Flag Editor
        ///ItemReceivedEditor=Received Item List Editor
        ///SimpleHexEditor=RAM Edit
        ///SysBotRAMEdit=SysBotUI
        ///SysBotUI=SysBotUI
        ///TerrainEditor=Terrain Editor
        ///AcreEditor.B_Cancel=Cancel
        ///AcreEditor.B_Export=Export
        ///AcreEditor.B_Import=Import
        ///AcreEditor.B_Save=Save
        ///AcreEditor.L_AcreList=Name Table:
        ///AcreEditor.L_Hovered=Hovered
        ///AcreEditor.L_X0=x
        ///AcreEditor.L_X1=1
        ///AcreEditor. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_jp {
            get {
                return ResourceManager.GetString("lang_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcreEditor=Acre Editor
        ///ActivityEditor=Record Editor
        ///BuildingEditor=Building Editor
        ///FieldItemEditor=Field Item Editor
        ///FlagEditor=Flag Editor
        ///ItemReceivedEditor=Received Item List Editor
        ///SimpleHexEditor=RAM Edit
        ///SysBotRAMEdit=SysBotUI
        ///SysBotUI=SysBotUI
        ///TerrainEditor=Terrain Editor
        ///AcreEditor.B_Cancel=Cancel
        ///AcreEditor.B_Export=Export
        ///AcreEditor.B_Import=Import
        ///AcreEditor.B_Save=Save
        ///AcreEditor.L_AcreList=Name Table:
        ///AcreEditor.L_Hovered=Hovered
        ///AcreEditor.L_X0=x
        ///AcreEditor.L_X1=1
        ///AcreEditor. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_zh {
            get {
                return ResourceManager.GetString("lang_zh", resourceCulture);
            }
        }
    }
}
