//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSE.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHSE.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 AcreEditor=Acre Editor
        ///ActivityEditor=Record Editor
        ///BuildingEditor=Building Editor
        ///FieldItemEditor=Field Item Editor
        ///FlagEditor=Flag Editor
        ///ItemReceivedEditor=Received Item List Editor
        ///PatternEditor=Pattern Editor
        ///PatternEditorPRO=Pro Design Editor
        ///PlayerItemEditor=Inventory Editor
        ///SimpleHexEditor=RAM Edit
        ///SingleObjectEditor=Property Editor
        ///SysBotRAMEdit=SysBotUI
        ///SysBotUI=SysBotUI
        ///TerrainEditor=Terrain Editor
        ///VillagerHouseEditor=Villager House Editor
        ///AcreEditor.B_Cancel=Cancel
        ///AcreEditor.B_E [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AcreEditor=Acre Editor
        ///ActivityEditor=Record Editor
        ///BuildingEditor=Building Editor
        ///FieldItemEditor=Field Item Editor
        ///FlagEditor=Flag Editor
        ///ItemReceivedEditor=Received Item List Editor
        ///PatternEditor=Pattern Editor
        ///PatternEditorPRO=Pro Design Editor
        ///PlayerItemEditor=Inventory Editor
        ///SimpleHexEditor=RAM Edit
        ///SingleObjectEditor=Property Editor
        ///SysBotRAMEdit=SysBotUI
        ///SysBotUI=SysBotUI
        ///TerrainEditor=Terrain Editor
        ///VillagerHouseEditor=Villager House Editor
        ///AcreEditor.B_Cancel=Cancel
        ///AcreEditor.B_E [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AcreEditor=Editor de Acres
        ///ActivityEditor=Editor de Actividad
        ///BuildingEditor=Editor de Edificios
        ///FieldItemEditor=Editor de Objetos (Terreno)
        ///FlagEditor=Editor de Flags
        ///ItemReceivedEditor=Editor de Objetos Recibidos
        ///PatternEditor=Pattern Editor
        ///PatternEditorPRO=Pro Design Editor
        ///PlayerItemEditor=Inventory Editor
        ///SimpleHexEditor=Editor de RAM
        ///SingleObjectEditor=Property Editor
        ///SysBotRAMEdit=SysBotUI
        ///SysBotUI=SysBotUI
        ///TerrainEditor=Editor de Terreno
        ///VillagerHouseEditor=Editor de Casas (Ciudadanos [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AcreEditor=Acre Editor
        ///ActivityEditor=Record Editor
        ///BuildingEditor=Building Editor
        ///FieldItemEditor=Field Item Editor
        ///FlagEditor=Flag Editor
        ///ItemReceivedEditor=Received Item List Editor
        ///PatternEditor=Pattern Editor
        ///PatternEditorPRO=Pro Design Editor
        ///PlayerItemEditor=Inventory Editor
        ///SimpleHexEditor=RAM Edit
        ///SingleObjectEditor=Property Editor
        ///SysBotRAMEdit=SysBotUI
        ///SysBotUI=SysBotUI
        ///TerrainEditor=Terrain Editor
        ///VillagerHouseEditor=Villager House Editor
        ///AcreEditor.B_Cancel=Cancel
        ///AcreEditor.B_E [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AcreEditor=Modifica Sezioni 
        ///ActivityEditor=Modifica Record 
        ///BuildingEditor=Modifica Edifici 
        ///FieldItemEditor=Modifica oggetti sul terreno
        ///FlagEditor=Modifica Flag
        ///ItemReceivedEditor=Modifica catalogo
        ///PatternEditor=Modifica pattern
        ///PatternEditorPRO=Modifica pattern Pro
        ///PlayerItemEditor=Modifica inventario
        ///SimpleHexEditor=Modifica RAM
        ///SingleObjectEditor=Modifica proprietà
        ///SysBotRAMEdit=SysBotUI
        ///SysBotUI=SysBotUI
        ///TerrainEditor=Editor del terreno
        ///VillagerHouseEditor=Editor casa del villager
        ///Acre [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AcreEditor=Acre Editor
        ///ActivityEditor=Record Editor
        ///BuildingEditor=Building Editor
        ///FieldItemEditor=Field Item Editor
        ///FlagEditor=Flag Editor
        ///ItemReceivedEditor=Received Item List Editor
        ///PatternEditor=Pattern Editor
        ///PatternEditorPRO=Pro Design Editor
        ///PlayerItemEditor=Inventory Editor
        ///SimpleHexEditor=RAM Edit
        ///SingleObjectEditor=Property Editor
        ///SysBotRAMEdit=SysBotUI
        ///SysBotUI=SysBotUI
        ///TerrainEditor=Terrain Editor
        ///VillagerHouseEditor=Villager House Editor
        ///AcreEditor.B_Cancel=Cancel
        ///AcreEditor.B_E [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lang_jp {
            get {
                return ResourceManager.GetString("lang_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AcreEditor=Acre Editor
        ///ActivityEditor=Record Editor
        ///BuildingEditor=Building Editor
        ///FieldItemEditor=Field Item Editor
        ///FlagEditor=Flag Editor
        ///ItemReceivedEditor=Received Item List Editor
        ///PatternEditor=Pattern Editor
        ///PatternEditorPRO=Pro Design Editor
        ///PlayerItemEditor=Inventory Editor
        ///SimpleHexEditor=RAM Edit
        ///SingleObjectEditor=Property Editor
        ///SysBotRAMEdit=SysBotUI
        ///SysBotUI=SysBotUI
        ///TerrainEditor=Terrain Editor
        ///VillagerHouseEditor=Villager House Editor
        ///AcreEditor.B_Cancel=Cancel
        ///AcreEditor.B_E [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AcreEditor=耕地编辑器
        ///ActivityEditor=成就编辑器
        ///BuildingEditor=建筑编辑器
        ///FieldItemEditor=地形编辑器
        ///FlagEditor=属性编辑器
        ///ItemReceivedEditor=收藏清单编辑器
        ///PatternEditor=设计编辑器
        ///PatternEditorPRO=专业设计编辑器
        ///PlayerItemEditor=道具编辑器
        ///SimpleHexEditor=十六进制编辑器
        ///SingleObjectEditor=属性编辑器
        ///SysBotRAMEdit=SysBot 界面
        ///SysBotUI=SysBot 界面
        ///TerrainEditor=地形编辑器
        ///VillagerHouseEditor=岛民房屋编辑器
        ///AcreEditor.B_Cancel=取消
        ///AcreEditor.B_Export=导出
        ///AcreEditor.B_Import=导入
        ///AcreEditor.B_Save=保存
        ///AcreEditor.L_AcreList=名称表:
        ///AcreEditor.L_Hovered=鼠标划上
        ///ActivityEditor. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lang_zhs {
            get {
                return ResourceManager.GetString("lang_zhs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AcreEditor=耕地編輯器
        ///ActivityEditor=成就編輯器
        ///BuildingEditor=建築編輯器
        ///FieldItemEditor=地皮編輯器
        ///FlagEditor=屬性編輯器
        ///ItemReceivedEditor=收藏清單編輯器
        ///PatternEditor=設計編輯器
        ///PatternEditorPRO=進階設計編輯器
        ///PlayerItemEditor=道具編輯器
        ///SimpleHexEditor=十六進位編輯器
        ///SingleObjectEditor=屬性編輯器
        ///SysBotRAMEdit=SysBot 介面
        ///SysBotUI=SysBot 介面
        ///TerrainEditor=地形編輯器
        ///VillagerHouseEditor=島民房屋編輯器
        ///AcreEditor.B_Cancel=取消
        ///AcreEditor.B_Export=匯出
        ///AcreEditor.B_Import=匯入
        ///AcreEditor.B_Save=儲存
        ///AcreEditor.L_AcreList=名稱表:
        ///AcreEditor.L_Hovered=鼠標劃上
        ///ActivityEditor. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lang_zht {
            get {
                return ResourceManager.GetString("lang_zht", resourceCulture);
            }
        }
    }
}
