//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSE.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHSE.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/berichan/NHSE-USB/releases/download/0.01/raw.zip.
        /// </summary>
        internal static string hosts_images {
            get {
                return ResourceManager.GetString("hosts_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AchievementEditor=Record Editor
        ///BuildingHelp=Building Help
        ///BulkSpawn=Bulk Spawn
        ///FieldItemEditor=Field Item Editor
        ///FlagEditor=Flag Editor
        ///ItemReceivedEditor=Received Item List Editor
        ///LandFlagEditor=Flag Editor
        ///MiscPlayerEditor=Misc Player Detail Editor
        ///MuseumEditor=Flag Editor
        ///PatternEditor=Pattern Editor
        ///PatternEditorPRO=Pro Design Editor
        ///PlayerHouseEditor=Player House Editor
        ///PlayerHouseFlagEditor=Flag Editor
        ///PlayerItemEditor=Inventory Editor
        ///ReactionEditor=Reaction List Editor
        ///RecipeListEdit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AchievementEditor=Record Editor
        ///BuildingHelp=Building Help
        ///BulkSpawn=Bulk Spawn
        ///FieldItemEditor=Field Item Editor
        ///FlagEditor=Flag Editor
        ///ItemReceivedEditor=Received Item List Editor
        ///LandFlagEditor=Flag Editor
        ///MiscPlayerEditor=Misc Player Detail Editor
        ///MuseumEditor=Flag Editor
        ///PatternEditor=Pattern Editor
        ///PatternEditorPRO=Pro Design Editor
        ///PlayerHouseEditor=Player House Editor
        ///PlayerHouseFlagEditor=Flag Editor
        ///PlayerItemEditor=Inventory Editor
        ///ReactionEditor=Reaction List Editor
        ///RecipeListEdit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AchievementEditor=Editor de Récords
        ///BuildingHelp=Ayuda de Construcción
        ///BulkSpawn=Aumentar Spawn
        ///FieldItemEditor=Editor de Objetos (Terreno)
        ///FlagEditor=Editor de Flags
        ///ItemReceivedEditor=Editor de Objetos Recibidos
        ///LandFlagEditor= Editor de Flags
        ///MuseumEditor=Editor de Flags
        ///PatternEditor=Editor de Patrones
        ///PatternEditorPRO=Editor de Diseño Pro
        ///PlayerHouseEditor=Editor de la Casa del Jugador
        ///PlayerHouseFlagEditor=Editor de Flags
        ///PlayerItemEditor=Editor de Inventario
        ///ReactionEditor=Editor de List [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AchievementEditor=Record Editor
        ///BuildingHelp=Building Help
        ///BulkSpawn=Bulk Spawn
        ///FieldItemEditor=Field Item Editor
        ///FlagEditor=Flag Editor
        ///ItemReceivedEditor=Received Item List Editor
        ///LandFlagEditor=Flag Editor
        ///MiscPlayerEditor=Misc Player Detail Editor
        ///MuseumEditor=Flag Editor
        ///PatternEditor=Pattern Editor
        ///PatternEditorPRO=Pro Design Editor
        ///PlayerHouseEditor=Player House Editor
        ///PlayerHouseFlagEditor=Flag Editor
        ///PlayerItemEditor=Inventory Editor
        ///ReactionEditor=Reaction List Editor
        ///RecipeListEdit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AchievementEditor=Modifica Record
        ///BuildingHelp=Aiuto Costruzione
        ///BulkSpawn=Genera in massa
        ///FieldItemEditor=Modifica oggetti sul terreno
        ///FlagEditor=Modifica Flag
        ///ItemReceivedEditor=Modifica catalogo
        ///LandFlagEditor=Modifica Flag
        ///MiscPlayerEditor=Modifica dettagli giocatore
        ///MuseumEditor=Modifica Flag
        ///PatternEditor=Modifica modelli
        ///PatternEditorPRO=Modifica modelli Pro
        ///PlayerHouseEditor=Modifica casa del giocatore
        ///PlayerHouseFlagEditor=Modifica Flag casa del giocatore
        ///PlayerItemEditor=Modifica inve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AchievementEditor=Record Editor
        ///BuildingHelp=Building Help
        ///BulkSpawn=Bulk Spawn
        ///FieldItemEditor=Field Item Editor
        ///FlagEditor=Flag Editor
        ///ItemReceivedEditor=Received Item List Editor
        ///LandFlagEditor=Flag Editor
        ///MiscPlayerEditor=Misc Player Detail Editor
        ///MuseumEditor=Flag Editor
        ///PatternEditor=Pattern Editor
        ///PatternEditorPRO=Pro Design Editor
        ///PlayerHouseEditor=Player House Editor
        ///PlayerHouseFlagEditor=Flag Editor
        ///PlayerItemEditor=Inventory Editor
        ///ReactionEditor=Reaction List Editor
        ///RecipeListEdit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_jp {
            get {
                return ResourceManager.GetString("lang_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AchievementEditor=Record Editor
        ///BuildingHelp=Building Help
        ///BulkSpawn=Bulk Spawn
        ///FieldItemEditor=Field Item Editor
        ///FlagEditor=Flag Editor
        ///ItemReceivedEditor=Received Item List Editor
        ///LandFlagEditor=Flag Editor
        ///MiscPlayerEditor=Misc Player Detail Editor
        ///MuseumEditor=Flag Editor
        ///PatternEditor=Pattern Editor
        ///PatternEditorPRO=Pro Design Editor
        ///PlayerHouseEditor=Player House Editor
        ///PlayerHouseFlagEditor=Flag Editor
        ///PlayerItemEditor=Inventory Editor
        ///ReactionEditor=Reaction List Editor
        ///RecipeListEdit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AchievementEditor=记录编辑器
        ///BuildingHelp=建筑帮助
        ///BulkSpawn=Bulk Spawn
        ///FieldItemEditor=地皮编辑器
        ///FlagEditor=属性编辑器
        ///ItemReceivedEditor=收藏清单编辑器
        ///LandFlagEditor=参数编辑器
        ///MiscPlayerEditor=杂项编辑器
        ///MuseumEditor=参数编辑器
        ///PatternEditor=设计编辑器
        ///PatternEditorPRO=专业设计编辑器
        ///PlayerHouseEditor=玩家房屋编辑器
        ///PlayerHouseFlagEditor=参数编辑器
        ///PlayerItemEditor=物品编辑器
        ///ReactionEditor=反应列表编辑器
        ///RecipeListEditor=Recipe List Editor
        ///SaveRoomFloorWallEditor=房间编辑器
        ///SimpleHexEditor=16进制编辑器
        ///SingleItemEditor=物品编辑器
        ///SingleObjectEditor=属性编辑器
        ///SysBotRAMEdit=Sys [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_zhs {
            get {
                return ResourceManager.GetString("lang_zhs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AchievementEditor=成就編輯器
        ///BuildingHelp=建築說明
        ///BulkSpawn=Bulk Spawn
        ///FieldItemEditor=地皮編輯器
        ///FlagEditor=屬性編輯器
        ///ItemReceivedEditor=目錄清單編輯器
        ///LandFlagEditor=參數編輯器
        ///MiscPlayerEditor=雜項編輯器
        ///MuseumEditor=博物館編輯器
        ///PatternEditor=設計編輯器
        ///PatternEditorPRO=專業設計編輯器
        ///PlayerHouseEditor=玩家房屋編輯器
        ///PlayerHouseFlagEditor=參數編輯器
        ///PlayerItemEditor=物品編輯器
        ///ReactionEditor=表情編輯器
        ///RecipeListEditor=Recipe List Editor
        ///SaveRoomFloorWallEditor=房間編輯器
        ///SimpleHexEditor=16進制編輯器
        ///SingleItemEditor=物品編輯器
        ///SingleObjectEditor=屬性編輯器
        ///SysBotRAMEdit=SysB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_zht {
            get {
                return ResourceManager.GetString("lang_zht", resourceCulture);
            }
        }
    }
}
