using System.Collections.Generic;
using static NHSE.Core.ItemClothGroup;

namespace NHSE.Core;

/// <summary>
/// Cloth group of items
/// </summary>
public enum ItemClothGroup : ushort
{
    None = 0x00,
    TopsTexTopCoatL = 0x12,
    TopsTexTopTshirtsHKungfu = 0x13,
    TopsTexOnepieceAlineNCheer = 0x14,
    TopsTexTopOuterLStajanBlue = 0x15,
    TopsTexTopTshirtsHNumberball3 = 0x16,
    TopsTexTopTshirtsHNumberball2 = 0x17,
    TopsTexOnepieceBalloonNSatin = 0x18,
    TopsTexTopTshirtsNCamisole = 0x19,
    TopsTexTopYshirtsLChina = 0x1A,
    TopsTexTopTshirtsLRaglan = 0x1B,
    TopsTexOnepieceAlineLTweed = 0x1C,
    TopsTexOnepieceAlineHPolkadotSpring = 0x1D,
    TopsTexOnepieceAlineNMuumuu = 0x1E,
    TopsTexOnepieceBoxLYosoiki = 0x1F,
    TopsTexOnepieceBoxNRetroGreen = 0x20,
    TopsTexTopTshirtsNBasketballshirtsPurple = 0x21,
    TopsTexTopOuterNKnit = 0x23,
    TopsTexTopOuterLDownjacketBlue = 0x25,
    TopsTexOnepieceAlineHYumeiro = 0x26,
    TopsTexOnepieceBoxLEnsembleBlue = 0x27,
    TopsTexTopYshirtsLWhite = 0x28,
    TopsTexOnepieceBalloonHPolkadotBlue = 0x29,
    TopsTexTopTshirtsHSailor = 0x2A,
    TopsTexTopOuterLParkaGray = 0x2B,
    TopsTexTopTshirtsLSmockTulip = 0x2C,
    TopsTexOnepieceAlineHFlowerPink = 0x2D,
    TopsTexOnepieceBalloonLLolita = 0x2E,
    SocksTexTights = 0x2F,
    SocksTexAmitights = 0x30,
    TopsTexOnepieceBoxLChidori = 0x31,
    TopsTexOnepieceBoxHParty = 0x32,
    TopsTexOnepieceBoxLBubbly = 0x33,
    TopsTexOnepieceBalloonNXmasRed = 0x34,
    TopsTexOnepieceBalloonHHoodRed = 0x35,
    TopsTexOnepieceBalloonHMaid = 0x36,
    TopsTexTopCoatLAcademicdress = 0x38,
    TopsTexOnepieceBalloonHWaitress = 0x3A,
    TopsTexTopYshirtsHWhite = 0x3B,
    TopsTexTopYshirtsNWhite = 0x3C,
    TopsTexOnepieceAlineLRabbit = 0x3D,
    TopsTexTopCoatLPirate = 0x3E,
    TopsTexOnepieceAlineLHeroine = 0x3F,
    TopsTexTopCoatLHanten = 0x40,
    TopsTexOnepieceBoxLBathrobes = 0x41,
    TopsTexOnepieceBalloonNBallet = 0x42,
    TopsTexOnepieceAlineLCat = 0x43,
    TopsTexOnepieceBalloonHTyrolean = 0x44,
    TopsTexOnepieceAlineNXmastreeNormal = 0x45,
    TopsTexTopCoatLRain = 0x46,
    TopsTexTopCoatLNoble = 0x47,
    TopsTexTopYshirtsHPolo = 0x48,
    TopsTexTopCoatLWhitecoat = 0x49,
    TopsTexTopCoatHCock = 0x4A,
    TopsTexTopCoatLCafe = 0x4B,
    TopsTexTopTshirtsHGym = 0x4C,
    TopsTexTopTshirtsNTanktop = 0x4D,
    TopsTexTopYshirtsLComedian = 0x4E,
    TopsTexTopYshirtsLRiders = 0x4F,
    TopsTexTopTshirtsNCamisoleprint = 0x50,
    TopsTexTopYshirtsLDenim = 0x51,
    TopsTexTopCoatHRubberapron = 0x52,
    TopsTexTopTshirtsHFishing = 0x53,
    TopsTexTopCoatLMouton = 0x54,
    TopsTexTopYshirtsLFlannel = 0x55,
    TopsTexTopYshirtsNDenim = 0x56,
    TopsTexTopCoatHApron = 0x57,
    TopsTexTopCoatLInfantry = 0x58,
    TopsTexOnepieceBoxNPrimitive = 0x59,
    TopsTexTopCoatLGunknight = 0x5A,
    TopsTexTopYshirtsHAloha = 0x5B,
    TopsTexTopTshirtsNCamisolelace = 0x5C,
    TopsTexTopOuterLJersey = 0x5D,
    TopsTexTopYshirtsLWestern = 0x5E,
    TopsTexTopTshirtsNEkiden = 0x5F,
    TopsTexTopYshirtsHChina = 0x60,
    TopsTexTopTshirtsHSoccer = 0x61,
    TopsTexTopOuterLSukajantiger = 0x62,
    TopsTexTopYshirtsHHappi = 0x63,
    TopsTexTopOuterLSukajandragon = 0x64,
    TopsTexTopTshirtsHCamouflage = 0x65,
    TopsTexTopTshirtsHCycle = 0x66,
    TopsTexTopTshirtsHChick = 0x67,
    TopsTexOnepieceDressLPrincess = 0x68,
    TopsTexOnepieceRibNKnit = 0x69,
    TopsTexTopYshirtsLArgyle = 0x6A,
    TopsTexTopYshirtsHExplorer = 0x6B,
    TopsTexTopYshirtsLJacketgaudy = 0x6C,
    TopsTexTopYshirtsLNecktie = 0x6D,
    TopsTexTopCoatHItamae = 0x6E,
    TopsTexTopYshirtsLBlazer = 0x6F,
    TopsTexTopCoatLKing = 0x70,
    TopsTexOnepieceAlineNStrawberry = 0x71,
    TopsTexOnepieceAlineNWatermelon = 0x72,
    TopsTexOnepieceAlineNOrange = 0x73,
    TopsTexOnepieceAlineNKiwi = 0x74,
    TopsTexOnepieceAlineNGrape = 0x75,
    TopsTexOnepieceAlineNPineapple = 0x76,
    BottomsTexPantsNormalSweat = 0x77,
    BottomsTexSkirtAlineTweed = 0x78,
    BottomsTexPantsNormalLeather = 0x7D,
    BottomsTexPantsNormalSlacks = 0x7E,
    BottomsTexPantsNormalJersey = 0x7F,
    BottomsTexPantsNormalBoder = 0x80,
    BottomsTexPantsNormalDenimholes = 0x81,
    TopsTexTopYshirtsLTwotone = 0x82,
    TopsTexTopTshirtsHNumberball1 = 0x83,
    TopsTexTopTshirtsHNumberball4 = 0x84,
    TopsTexTopTshirtsHNumberball5 = 0x85,
    TopsTexTopTshirtsHNumberball6 = 0x86,
    TopsTexTopTshirtsHNumberball7 = 0x87,
    TopsTexTopTshirtsHNumberball8 = 0x88,
    TopsTexTopTshirtsHNumberball9 = 0x89,
    TopsTexTopYshirtsLTiedsweater = 0x8A,
    TopsTexTopYshirtsLSportsjersey = 0x8B,
    BottomsTexPantsNormalSportsjersey = 0x8C,
    TopsTexOnepieceDressNWedding = 0x8D,
    BottomsTexSkirtAlineKilt = 0x8E,
    TopsTexTopYshirtsLGilet = 0x8F,
    BottomsTexSkirtAlineSailorNavy = 0x90,
    BottomsTexPantsNormalCamouflage = 0x91,
    TopsTexOnepieceBoxHNurse = 0x92,
    TopsTexTopYshirtsHNurse = 0x93,
    BottomsTexPantsWideCargo = 0x94,
    BottomsTexPantsWideSusomise = 0x95,
    TopsTexOnepieceOverallLPajama = 0x96,
    TopsTexTopTshirtsNBorder = 0x97,
    BottomsTexSkirtAlineLace = 0x98,
    TopsTexOnepieceBalloonLCorsetPurple = 0x99,
    TopsTexOnepieceBoxLShirt = 0x9A,
    TopsTexOnepieceAlineNShirt = 0x9B,
    TopsTexTopYshirtsLTuxedo = 0x9C,
    TopsTexTopCoatLSanta = 0x9D,
    BottomsTexPantsNormalSanta = 0x9E,
    TopsTexTopCoatLMorningcoat = 0x9F,
    BottomsTexPantsWideSchool = 0xA0,
    BottomsTexPantsNormalSlacksgaudy = 0xA1,
    TopsTexOnepieceOverallLJockey = 0xA2,
    TopsTexOnepieceOverallLBear = 0xA3,
    TopsTexOnepieceOverallLFirefighter = 0xA4,
    TopsTexOnepieceOverallLFrog = 0xA5,
    TopsTexOnepieceOverallLKappa = 0xA6,
    TopsTexOnepieceDressLClassic = 0xA7,
    TopsTexOnepieceAlongNNile = 0xA8,
    TopsTexOnepieceOverallLWorkwear = 0xA9,
    TopsTexOnepieceOverallLClown = 0xAA,
    TopsTexOnepieceOverallLHero = 0xAB,
    TopsTexOnepieceOverallHJinbei = 0xAC,
    TopsTexOnepieceOverallLNinja = 0xAD,
    TopsTexOnepieceOverallLDragon = 0xAE,
    BottomsTexPantsWideCowboy = 0xAF,
    TopsTexOnepieceOverallLHotel = 0xB0,
    TopsTexTopYshirtsLTailored = 0xB1,
    TopsTexOnepieceBoxLAttendant = 0xB2,
    TopsTexTopYshirtsLVest = 0xB3,
    TopsTexOnepieceAlongLWitch = 0xB4,
    TopsTexOnepieceBlongLAodai = 0xB5,
    TopsTexOnepieceBlongLKappogi = 0xB6,
    TopsTexOnepieceAlongLChimachogori = 0xB7,
    AccessoryMouthBeakYellow = 0xB8,
    AccessoryMouthBeard = 0xB9,
    TopsTexOnepieceOverallLPolice = 0xBA,
    TopsTexOnepieceBlongHToga = 0xBB,
    TopsTexOnepieceKimonoLUme = 0xBC,
    TopsTexOnepieceAlongLGothic = 0xBD,
    TopsTexOnepieceBoxNGreece = 0xBE,
    TopsTexTopTshirtsHKanji = 0xBF,
    TopsTexOnepieceAlineLMold = 0xC0,
    TopsTexOnepieceBlongHEgypt = 0xC1,
    TopsTexTopYshirtsLCardiganyshirt = 0xC2,
    TopsTexTopOuterLArgyle = 0xC3,
    TopsTexTopOuterLFlowerknit = 0xC4,
    TopsTexTopOuterLTennis = 0xC5,
    TopsTexOnepieceOverallNArabia = 0xC6,
    TopsTexOnepieceOverallLMummy = 0xC7,
    TopsTexOnepieceOverallLBone = 0xC8,
    TopsTexOnepieceOverallNWrestling = 0xC9,
    TopsTexOnepieceOverallLBaseball = 0xCA,
    TopsTexOnepieceOverallLPilot = 0xCB,
    TopsTexOnepieceOverallLBull = 0xCC,
    TopsTexOnepieceDressHHolland = 0xCD,
    TopsTexTopOuterLNordic = 0xCE,
    TopsTexTopOuterLSnow = 0xCF,
    TopsTexTopOuterLNordiccardigan = 0xD0,
    TopsTexTopOuterLAran = 0xD1,
    TopsTexTopOuterLYumekawa = 0xD2,
    TopsTexOnepieceOverallLSpace = 0xD3,
    TopsTexTopOuterLArancardigan = 0xD4,
    TopsTexOnepieceOverallLRacer = 0xD5,
    TopsTexOnepieceBoxNSequins = 0xD6,
    TopsTexOnepieceAlineHSuspendersskirt = 0xD7,
    TopsTexOnepieceBoxLJumperskirtuniform = 0xD8,
    TopsTexTopCoatLNocollar = 0xD9,
    TopsTexTopYshirtsLRugby = 0xDA,
    TopsTexOnepieceOverallLSaropetto = 0xDB,
    TopsTexTopOuterLSweat = 0xDC,
    TopsTexOnepieceBalloonHMarine = 0xDD,
    TopsTexTopTshirtsLHenley = 0xDE,
    TopsTexTopTshirtsHGillet = 0xDF,
    TopsTexTopCoatHStripeshirts = 0xE0,
    TopsTexTopCoatLCoverall = 0xE1,
    TopsTexOnepieceBlongHSally = 0xE2,
    TopsTexOnepieceBalloonHStrange = 0xE3,
    TopsTexTopYshirtsHCuba = 0xE4,
    TopsTexTopCoatLPcoat = 0xE5,
    TopsTexTopYshirtsLNocollar = 0xE6,
    TopsTexTopYshirtsLWork = 0xE7,
    TopsTexOnepieceAlongLBustier = 0xE8,
    TopsTexTopYshirtsHBowling = 0xE9,
    TopsTexTopTshirtsLVnecksweater = 0xEA,
    TopsTexOnepieceBalloonNFairy = 0xEB,
    ShoesSandalGetaBlack = 0xEC,
    TopsTexTopYshirtsLFleece = 0xED,
    TopsTexTopYshirtsLTweed = 0xEE,
    TopsTexOnepieceOverallLSuspenders = 0xEF,
    BottomsTexPantsWideTweed = 0xF0,
    TopsTexTopTshirtsLLayeredtshirts = 0xF1,
    TopsTexTopTshirtsHLace = 0xF2,
    TopsTexTopCoatLChester = 0xF3,
    TopsTexTopCoatLChestercheck = 0xF4,
    BottomsTexPantsHalfCargo = 0xF5,
    TopsTexTopTshirtsHBigstole = 0xF6,
    TopsTexOnepieceOverallHDwarf = 0xF7,
    BottomsTexPantsHotRunning = 0xF8,
    TopsTexTopYshirtsLPrince = 0xF9,
    TopsTexTopTshirtsNFitness = 0xFA,
    TopsTexTopOuterLFlight = 0xFB,
    TopsTexTopTshirtsHTiedye = 0xFC,
    TopsTexTopYshirtsLBoavest = 0xFD,
    TopsTexTopCoatLQuilting = 0xFE,
    BottomsTexSkirtLongPleats = 0xFF,
    BottomsTexSkirtAlineTennis = 0x100,
    AccessoryGlass = 0x101,
    AccessoryGlassSquare = 0x102,
    AccessoryGlassHeart = 0x103,
    AccessoryGlassThurmont = 0x104,
    AccessoryGlassOctagon = 0x105,
    AccessoryGlassStar = 0x106,
    AccessoryGlassBoston = 0x107,
    AccessoryGlassTriangle = 0x108,
    BottomsTexSkirtBoxDenim = 0x109,
    TopsTexTopTshirtsLPeasant = 0x10A,
    TopsTexOnepieceAlongHNegligee = 0x10B,
    TopsTexOnepieceOverallLJudo = 0x10C,
    BottomsTexPantsHotDenimholes = 0x10D,
    BottomsTexSkirtLongDot = 0x10E,
    TopsTexTopTshirtsNTubetop = 0x10F,
    BottomsTexPantsWideHickory = 0x110,
    BottomsTexPantsNormalChain = 0x111,
    BottomsTexPantsNormalDown = 0x112,
    BottomsTexSkirtLongChino = 0x113,
    TopsTexOnepieceAlineLBorder = 0x114,
    AccessoryGlassDoublebridge = 0x115,
    TopsTexOnepieceBalloonNBubble = 0x116,
    TopsTexOnepieceAlineHLinen = 0x117,
    BottomsTexSkirtBoxDown = 0x118,
    TopsTexTopTshirtsNMuscle = 0x119,
    TopsTexOnepieceKimonoLWizard = 0x11A,
    BottomsTexPantsHotDenim = 0x11B,
    TopsTexTopTshirtsHBorder = 0x11C,
    TopsTexTopOuterLDownvest = 0x11D,
    AccessoryGlassBottle = 0x11E,
    BottomsTexSkirtBoxSweat = 0x11F,
    TopsTexTopYshirtsLCoach = 0x120,
    TopsTexTopCoatLGowncoat = 0x121,
    TopsTexTopTshirtsLChidori = 0x122,
    TopsTexOnepieceAlineNHalterneckstripe = 0x123,
    TopsTexTopTshirtsHPocketshirts = 0x124,
    TopsTexOnepieceKimonoLMiko = 0x125,
    TopsTexOnepieceBalloonHPirate = 0x126,
    BottomsTexSkirtBoxCorduroy = 0x127,
    BottomsTexPantsWideGaucho = 0x128,
    TopsTexOnepieceBoxNModern = 0x129,
    TopsTexTopYshirtsLSlimknit = 0x12A,
    BottomsTexSkirtBoxLeather = 0x12B,
    TopsTexTopOuterLCollegecardigan = 0x12C,
    BottomsTexSkirtBoxFringe = 0x12D,
    TopsTexOnepieceKimonoLHakama = 0x12E,
    TopsTexTopTshirtsHKnot = 0x12F,
    TopsTexOnepieceOverallLTights = 0x130,
    BottomsTexPantsWideDenim = 0x131,
    TopsTexTopTshirtsHGoldprint = 0x132,
    TopsTexOnepieceOverallLWaders = 0x133,
    BottomsTexPantsNormalChinashort = 0x134,
    BottomsTexPantsNormalChina = 0x135,
    BottomsTexPantsWideKungfu = 0x136,
    TopsTexOnepieceBalloonHMagical = 0x137,
    BottomsTexSkirtBoxGrass = 0x138,
    TopsTexOnepieceAlineLBolerocoat = 0x139,
    TopsTexOnepieceBoxLOffice = 0x13A,
    AccessoryGlassCrack = 0x13B,
    TopsTexTopTshirtsLAlphabet = 0x13C,
    TopsTexOnepieceAlongNPearl = 0x13D,
    TopsTexOnepieceKimonoLKinagashi = 0x13E,
    TopsTexTopOuterLSukajanhawk = 0x13F,
    TopsTexOnepieceBalloonHSimple = 0x140,
    TopsTexOnepieceOverallLSimple = 0x141,
    TopsTexOnepieceBalloonNBunny = 0x142,
    TopsTexOnepieceOverallLFleecepajama = 0x143,
    TopsTexOnepieceAlongLLeathercoat = 0x144,
    TopsTexOnepieceBoxNBathtowel = 0x145,
    TopsTexTopYshirtsLSuitsmen = 0x146,
    BottomsTexPantsWideBellbottoms = 0x147,
    TopsTexTopYshirtsLGakuran = 0x148,
    TopsTexTopYshirtsLGakuranopen = 0x149,
    TopsTexTopCoatLPoncho = 0x14A,
    BottomsTexPantsWideFrilled = 0x14B,
    BottomsTexPantsHotYacht = 0x14C,
    BottomsTexPantsHalfMulticolor = 0x14D,
    BottomsTexPantsHalfFormal = 0x14E,
    BottomsTexSkirtBoxLeopard = 0x14F,
    BottomsTexSkirtLongCheck = 0x150,
    TopsTexTopCoatLVampire = 0x151,
    TopsTexOnepieceBoxLAutumncheck = 0x152,
    BottomsTexPantsNormalNoble = 0x153,
    TopsTexOnepieceBalloonNBlockcheck = 0x154,
    TopsTexTopOuterLMaone = 0x155,
    TopsTexTopOuterLCamo = 0x156,
    TopsTexOnepieceAlongLFrilled = 0x157,
    BottomsTexPantsHalfAloha = 0x158,
    TopsTexOnepieceBalloonNIdleeightys = 0x159,
    TopsTexTopYshirtsLHanten = 0x15A,
    BottomsTexPantsNormalCropped = 0x15B,
    TopsTexOnepieceBoxLBohemian = 0x15C,
    BottomsTexSkirtAlineFrilled = 0x15D,
    TopsTexTopOuterLMohair = 0x15E,
    TopsTexTopOuterLSpaceparker = 0x15F,
    TopsTexTopTshirtsHBaseball = 0x160,
    TopsTexTopCoatLInparker = 0x161,
    TopsTexTopTshirtsNTraining = 0x162,
    TopsTexTopCoatLMod = 0x163,
    TopsTexTopOuterLParkertshirt = 0x164,
    TopsTexOnepieceRibLSwitchsweat = 0x165,
    AccessoryGlassMask = 0x166,
    BottomsTexSkirtAlineTweedfrill = 0x167,
    TopsTexTopCoatLHeartapron = 0x168,
    BottomsTexPantsWideEasy = 0x169,
    TopsTexOnepieceRibNSheep = 0x16A,
    TopsTexOnepieceBalloonNSunflower = 0x16B,
    TopsTexTopCoatLPrince = 0x16C,
    BottomsTexSkirtBoxCamo = 0x16D,
    TopsTexTopYshirtsHTraffic = 0x16E,
    TopsTexTopCoatLTailcoat = 0x16F,
    TopsTexOnepieceOverallHTyrolean = 0x170,
    BottomsTexPantsHotCulotte = 0x171,
    TopsTexTopOuterLNative = 0x172,
    TopsTexTopTshirtsHAmericanfootball = 0x173,
    TopsTexTopYshirtsLSki = 0x174,
    TopsTexOnepieceOverallLStarsinger = 0x175,
    BottomsTexPantsWideSki = 0x176,
    AccessoryMouthMask = 0x177,
    AccessoryGlassEyepatch = 0x178,
    AccessoryGlassGogglesski = 0x179,
    AccessoryGlassGoggles = 0x17A,
    AccessoryGlassRetro = 0x17B,
    AccessoryGlassPatch = 0x17C,
    AccessoryGlassSports = 0x17D,
    AccessoryGlassPilot = 0x17E,
    AccessoryGlassTortoiseshell = 0x17F,
    AccessoryGlassMini = 0x180,
    AccessoryGlassMonocle = 0x181,
    AccessoryGlassThreed = 0x182,
    AccessoryGlassBlind = 0x183,
    TopsTexTopCoatLAnimal = 0x184,
    TopsTexOnepieceBoxNLayered = 0x185,
    TopsTexOnepieceBoxHTiger = 0x186,
    TopsTexOnepieceRibLParkershirt = 0x187,
    TopsTexTopCoatLRetro = 0x188,
    TopsTexOnepieceOverallLRompers = 0x189,
    TopsTexOnepieceOverallLBondage = 0x18A,
    BottomsTexPantsHalfOutdoor = 0x18B,
    TopsTexOnepieceOverallLSuper = 0x18C,
    AccessoryMouthCat = 0x18D,
    TopsTexOnepieceDressHChinapoblana = 0x18E,
    BottomsTexPantsNormalBondage = 0x18F,
    TopsTexTopTshirtsNHula = 0x190,
    BottomsTexPantsHalfEthnic = 0x191,
    TopsTexTopCoatLHippie = 0x192,
    TopsTexOnepieceRibLShawl = 0x193,
    BottomsTexPantsWideKnee = 0x194,
    AccessoryMouthCucumber = 0x195,
    AccessoryMouthSanta = 0x196,
    AccessoryGlassmouthNose = 0x197,
    AccessoryGlassmouthBeard = 0x198,
    BottomsTexSkirtLongTiered = 0x199,
    TopsTexTopYshirtsLCareer = 0x19A,
    BottomsTexSkirtBoxCareer = 0x19B,
    BottomsTexSkirtLongDrape = 0x19C,
    TopsTexOnepieceBalloonHDolly = 0x19D,
    TopsTexTopYshirtsLChimayo = 0x19E,
    AccessoryGlassBirthday = 0x19F,
    TopsTexOnepieceOverallLReindeer = 0x1A0,
    AccessoryGlassmouthPack = 0x1A1,
    AccessoryGlassEyes = 0x1A2,
    BottomsTexPantsNormalCycle = 0x1A3,
    BottomsTexPantsHalfSurf = 0x1A4,
    BottomsTexPantsHotLace = 0x1A5,
    BottomsTexPantsHalfJersey = 0x1A6,
    TopsTexTopCoatLKuruta = 0x1A7,
    TopsTexOnepieceBlongLShirt = 0x1A8,
    TopsTexTopOuterLPullover = 0x1A9,
    BottomsTexPantsHotThai = 0x1AA,
    BottomsTexPantsHotDotgold = 0x1AB,
    TopsTexTopYshirtsLTweedvest = 0x1AC,
    BottomsTexSkirtLongWrap = 0x1AD,
    BottomsTexSkirtLongEmbroidery = 0x1AE,
    BottomsTexSkirtLongGeometric = 0x1AF,
    AccessoryGlassmouthDiver = 0x1B0,
    AccessoryGlassCyber = 0x1B1,
    TopsTexTopOuterLMuffler = 0x1B2,
    TopsTexTopCoatLMuffler = 0x1B3,
    TopsTexOnepieceBoxNStandard = 0x1B4,
    TopsTexOnepieceAlineLRetro = 0x1B5,
    TopsTexTopCoatHWaistshirt = 0x1B6,
    TopsTexOnepieceBoxHTshirts = 0x1B7,
    TopsTexTopCoatNSequins = 0x1B8,
    AccessoryGlassDance = 0x1B9,
    TopsTexOnepieceOverallLVisual = 0x1BA,
    TopsTexTopCoatLLeathertrench = 0x1BB,
    TopsTexTopOuterLReindeer = 0x1BC,
    TopsTexTopYshirtsHKnot = 0x1BD,
    TopsTexOnepieceBalloonHLace = 0x1BE,
    TopsTexTopCoatLSoutiencollar = 0x1BF,
    TopsTexTopOuterLHighsence = 0x1C0,
    TopsTexTopYshirtsLCowboy = 0x1C1,
    TopsTexOnepieceRibNCaterpillar = 0x1C2,
    TopsTexTopYshirtsLBustier = 0x1C3,
    TopsTexOnepieceBoxLHouse = 0x1C4,
    TopsTexOnepieceBoxLForest = 0x1C5,
    TopsTexOnepieceOverallHRugby = 0x1C6,
    TopsTexOnepieceBlongNSlip = 0x1C7,
    TopsTexOnepieceOverallLPlatearmorIron = 0x1C8,
    TopsTexOnepieceAlongLDowncoat = 0x1C9,
    TopsTexOnepieceOverallLPlatearmorGold = 0x1CA,
    BottomsTexPantsWideSatin = 0x1CB,
    TopsTexOnepieceAlineLPcoat = 0x1CC,
    TopsTexTopOuterLRainbow = 0x1CD,
    TopsTexOnepieceAlongHCachecoeur = 0x1CE,
    AccessoryGlassLoose = 0x1CF,
    TopsTexTopOuterLBlouson = 0x1D0,
    TopsTexTopCoatNShirt = 0x1D1,
    AccessoryMouthRabbit = 0x1D2,
    TopsTexTopCoatLCoadigan = 0x1D3,
    BottomsTexPantsWideCorduroy = 0x1D4,
    TopsTexOnepieceOverallLVolendam = 0x1D5,
    TopsTexOnepieceRibLBore = 0x1D6,
    TopsTexTopCoatLPatchwork = 0x1D7,
    TopsTexOnepieceBlongLBalmakarn = 0x1D8,
    AccessoryGlassRound = 0x1D9,
    AccessoryGlassButterfly = 0x1DA,
    AccessoryGlassOval = 0x1DB,
    TopsTexTopTshirtsLEarphone = 0x1DC,
    TopsTexOnepieceOverallHArabia = 0x1DD,
    BottomsTexSkirtBoxLace = 0x1DE,
    TopsTexTopTshirtsLMulti = 0x1DF,
    BottomsTexSkirtAlineFlare = 0x1E0,
    TopsTexTopYshirtsHMadras = 0x1E1,
    TopsTexOnepieceAlongNEthnic = 0x1E2,
    TopsTexOnepieceOverallNCombinaison = 0x1E3,
    AccessoryGlassDot = 0x1E4,
    AccessoryMouthPig = 0x1E5,
    TopsTexOnepieceKimonoLIcequeen = 0x1E6,
    AccessoryGlassmouthGasmask = 0x1E7,
    TopsTexOnepieceDressLNordic = 0x1E8,
    AccessoryMouthRice = 0x1E9,
    TopsTexOnepieceOverallLMariachi = 0x1EA,
    TopsTexOnepieceBoxLMarble = 0x1EB,
    TopsTexOnepieceAlongNMermaid = 0x1EC,
    TopsTexOnepieceBlongLHippie = 0x1ED,
    AccessoryGlassVenetian = 0x1EE,
    TopsTexTopCoatNTanktunic = 0x1EF,
    AccessoryGlassWood = 0x1F0,
    AccessoryMouthCrow = 0x1F1,
    AccessoryMouthRollingmustache = 0x1F2,
    TopsTexOnepieceRibLCardigan = 0x1F4,
    TopsTexTopYshirtsNRibnoncami = 0x1F5,
    AccessoryMouthBeardChin = 0x1F6,
    AccessoryMouthBandage = 0x1F7,
    AccessoryGlassmouthPierrot = 0x1F8,
    AccessoryMouthBeardRound = 0x1F9,
    TopsTexTopOuterLFleece = 0x1FA,
    TopsTexTopCoatLDetective = 0x1FB,
    AccessoryMouthLeaf = 0x1FC,
    AccessoryGlassRhinestone = 0x1FD,
    AccessoryGlassHeromask = 0x1FE,
    AccessoryGlassSteampunk = 0x1FF,
    TopsTexOnepieceBalloonHAngel = 0x200,
    TopsTexTopTshirtsLLoose = 0x201,
    TopsTexOnepieceOverallLDevil = 0x202,
    ShoesSandalShower = 0x203,
    TopsTexTopYshirtsLOpencollar = 0x204,
    ShoesLowcutLeathersneker = 0x205,
    TopsTexTopTshirtsHMeme = 0x206,
    SocksTexRibbon = 0x207,
    ShoesHighcutMouton = 0x208,
    ShoesLowcutEnamelpumps = 0x209,
    ShoesLowcutLoafers = 0x20A,
    ShoesSandalCrossbelt = 0x20B,
    TopsTexTopYshirtsLQuilting = 0x20C,
    TopsTexOnepieceAlongNStripe = 0x20D,
    ShoesLowcutBusiness = 0x20E,
    TopsTexOnepieceAlineLJumperskirt = 0x20F,
    ShoesKneeVelour = 0x210,
    ShoesKneeRainboots = 0x211,
    ShoesSandalZori = 0x212,
    TopsTexTopOuterLSkidown = 0x213,
    TopsTexOnepieceAlineNLace = 0x214,
    CapHatSchool = 0x215,
    TopsTexOnepieceBalloonNClover = 0x216,
    SocksTexSneakerin = 0x217,
    SocksTexAlan = 0x218,
    SocksTexSequins = 0x219,
    SocksTexLeggings = 0x21A,
    SocksTexDenimleggings = 0x21B,
    SocksTexLine = 0x21C,
    SocksTexGarter = 0x21D,
    SocksTexNordic = 0x21E,
    SocksTexTabi = 0x21F,
    TopsTexTopYshirtsLFactory = 0x220,
    TopsTexTopOuterLBobble = 0x221,
    TopsTexOnepieceDressLLady = 0x222,
    TopsTexTopTshirtsLQuiet = 0x223,
    TopsTexTopCoatLAnorak = 0x224,
    TopsTexTopYshirtsLMultivest = 0x225,
    CapHatNewyear = 0x226,
    CapHatBirthday = 0x227,
    CapOrnamentTHyacinth1 = 0x228,
    CapOrnamentTHyacinth2 = 0x229,
    CapOrnamentTHyacinth3 = 0x22A,
    CapOrnamentAnemones1 = 0x22B,
    CapOrnamentAnemones2 = 0x22C,
    CapOrnamentAnemones3 = 0x22D,
    CapOrnamentTulip1 = 0x22E,
    CapOrnamentTulip2 = 0x22F,
    CapOrnamentTulip3 = 0x230,
    CapOrnamentPansy1 = 0x231,
    CapOrnamentPansy2 = 0x232,
    CapOrnamentPansy3 = 0x233,
    CapOrnamentCosmos1 = 0x234,
    CapOrnamentCosmos2 = 0x235,
    CapOrnamentCosmos3 = 0x236,
    CapOrnamentRose1 = 0x237,
    CapOrnamentRose2 = 0x238,
    CapOrnamentRose3 = 0x239,
    CapOrnamentLily1 = 0x23A,
    CapOrnamentLily2 = 0x23B,
    CapOrnamentLily3 = 0x23C,
    CapOrnamentChrysanthemum1 = 0x23D,
    CapOrnamentChrysanthemum2 = 0x23E,
    CapOrnamentChrysanthemum3 = 0x23F,
    TopsTexTopOuterLSnowcrystal = 0x240,
    TopsTexTopTshirtsLDamage = 0x241,
    TopsTexOnepieceOverallNWrestler = 0x242,
    CapHatSilkhat = 0x243,
    CapHatMeshcap = 0x244,
    TopsTexTopCoatLSamurai = 0x245,
    TopsTexOnepieceBlongLChina = 0x246,
    TopsTexTopCoatLHandcover = 0x247,
    TopsTexOnepieceOverallLOgre = 0x248,
    TopsTexTopCoatLThiefBlack = 0x249,
    TopsTexOnepieceAlineNSpace = 0x24A,
    CapHatExpedition = 0x24B,
    CapHatBachelor = 0x24C,
    CapHatSombrero = 0x24D,
    CapHatSafetyhat = 0x24E,
    CapHatCock = 0x24F,
    CapHatPolice = 0x250,
    CapHatPirate = 0x251,
    CapHatAjiro = 0x252,
    CapHatUshanka = 0x253,
    CapHatTriangle = 0x254,
    CapHatKnitcap = 0x255,
    CapHatHunting = 0x256,
    CapHatWorkcap = 0x257,
    SocksTexFootcover = 0x258,
    SocksTexMixtweed = 0x259,
    SocksTexLegwarmer = 0x25A,
    SocksTexCompression = 0x25B,
    SocksTexFolded = 0x25C,
    SocksTexFrilledknee = 0x25D,
    SocksTexLace = 0x25E,
    SocksTexFrilled = 0x25F,
    SocksTexHoletights = 0x260,
    SocksTexFootball = 0x261,
    SocksTexHole = 0x262,
    SocksTexBobble = 0x263,
    SocksTexMultiblock = 0x264,
    SocksTexFluffy = 0x265,
    AccessoryGlassHmd = 0x266,
    AccessoryGlassNightvision = 0x267,
    TopsTexTopYshirtsLKids = 0x268,
    CapHatSailor = 0x269,
    CapHatViking = 0x26A,
    SockstTexOverlapping = 0x26B,
    SocksTexHandknit = 0x26C,
    SocksTexAerobics = 0x26D,
    SocksTexPucker = 0x26E,
    SocksTexBorder = 0x26F,
    SocksTexOnepoint = 0x270,
    SocksTexKids = 0x271,
    SocksTexCrocheting = 0x272,
    SocksTexSpider = 0x273,
    SocksTexEmbroidery = 0x274,
    SocksTexRun = 0x275,
    AccessoryMouthDog = 0x276,
    CapHatWitch = 0x277,
    CapHatDenim = 0x278,
    CapHatCycle = 0x279,
    CapHatOutdoor = 0x27A,
    CapHatKankanbo = 0x27B,
    CapHatBeret = 0x27C,
    CapHatOrange = 0x27D,
    CapHatKiwi = 0x27E,
    CapHatStrawberry = 0x27F,
    CapHatGrape = 0x280,
    CapHatPineapple = 0x281,
    CapHatWatermelon = 0x282,
    CapHatItamae = 0x284,
    CapHatCyclemet = 0x285,
    CapHatSwim = 0x286,
    CapHatChina = 0x287,
    BottomsTexPantsWideChino = 0x288,
    BottomsTexPantsNormalChemical = 0x289,
    TopsTexOnepieceOverallNHotdog = 0x28A,
    TopsTexOnepieceOverallLFarmer = 0x28B,
    TopsTexTopOuterLChemical = 0x28C,
    TopsTexTopTshirtsLLive = 0x28D,
    TopsTexTopCoatLStraw = 0x28E,
    TopsTexTopOuterLRepresent = 0x28F,
    CapHatTulip = 0x290,
    CapHatBandana = 0x291,
    CapHatTyrolean = 0x292,
    CapHatBowler = 0x293,
    CapHatStraw = 0x294,
    CapHatShowercap = 0x295,
    CapHatFelt = 0x296,
    CapHatSimple = 0x297,
    CapHatSports = 0x298,
    CapHatNightcap = 0x299,
    CapHatSanta = 0x29A,
    CapHatCrown = 0x29B,
    CapHatPaper = 0x29C,
    CapHatTowel = 0x29D,
    CapHatAcorn = 0x29E,
    CapHatCombat = 0x29F,
    TopsTexTopYshirtsLCool = 0x2A1,
    CapHatHokkamuri = 0x2A2,
    CapHatCowl = 0x2A3,
    CapHatMummy = 0x2A4,
    CapHatRabbit = 0x2A5,
    CapHatCat = 0x2A6,
    CapHatFaceknit = 0x2A7,
    CapHatSkull = 0x2A8,
    CapHatShallow = 0x2A9,
    CapHatBear = 0x2AA,
    CapHatKappa = 0x2AB,
    CapHatCaptain = 0x2AC,
    CapHatCasquette = 0x2AD,
    CapFullfaceKnightIron = 0x2AE,
    CapCostumeFrog = 0x2AF,
    CapHatWizard = 0x2B0,
    CapHatBalloon = 0x2B1,
    BottomsTexPantsWideCool = 0x2B2,
    CapMaskOgre = 0x2B3,
    CapFullfaceKnightGold = 0x2B4,
    TopsTexTopPuffHFrill = 0x2B6,
    TopsTexOnepieceSalopetteLAllinone = 0x2B7,
    CapHatElegant = 0x2B8,
    CapCostumeFootball = 0x2B9,
    CapBangsFirefighter = 0x2BA,
    CapMaskWelder = 0x2BB,
    TopsTexTopOuterLChristmas = 0x2BC,
    CapHatClown = 0x2BD,
    CapCostumeSamurai = 0x2BE,
    TopsTexOnepieceOverallLMuscle = 0x2BF,
    CapHatVolendam = 0x2C0,
    ShoesLowcutTrekking = 0x2C1,
    CapHelmetPilot = 0x2C2,
    CapBangsBonnet = 0x2C3,
    CapCostumeNinja = 0x2C4,
    CapHelmetBaseballBlack = 0x2C5,
    CapCostumeJockey = 0x2C6,
    CapCostumeWrestling = 0x2C7,
    CapBangsSausage = 0x2C8,
    CapBangsEarknit = 0x2C9,
    CapHatDetective = 0x2CA,
    TopsTexOnepieceOverallLCyber = 0x2CB,
    TopsTexOnepieceFigure = 0x2CC,
    CapCostumeAstronaut = 0x2CD,
    CapMaskPaint = 0x2CE,
    CapHatStrawhat = 0x2CF,
    CapHatTengallon = 0x2D0,
    TopsTexOnepieceOverallLFigure = 0x2D1,
    SocksTexCharacter = 0x2D3,
    CapHatSnowknit = 0x2D4,
    CapHatColorful = 0x2D5,
    BottomsTexPantsHalfComic = 0x2D6,
    BottomsTexPantsNormalMonpe = 0x2D7,
    BottomsTexPantsWideRain = 0x2D8,
    BottomsTexSkirtBoxAran = 0x2D9,
    BottomsTexSkirtAlineFur = 0x2DA,
    BottomsTexPantsNormalSwewtfrill = 0x2DB,
    BottomsTexSkirtLongSweat = 0x2DC,
    BottomsTexSkirtBoxBoa = 0x2DD,
    BottomsTexPantsHalfBoa = 0x2DE,
    BottomsTexSkirtAlineLeather = 0x2DF,
    BottomsTexSkirtLongLace = 0x2E0,
    BottomsTexSkirtAlineTutu = 0x2E1,
    CapHelmetHero = 0x2E2,
    TopsTexOnepieceOverallLPowered = 0x2E3,
    TopsTexOnepieceAlongLRenaissance = 0x2E4,
    CapHelmetTurban = 0x2E5,
    CapCostumeGogglehelmet = 0x2E6,
    TopsTexTopYshirtsLGlass = 0x2E7,
    TopsTexTopYshirtsLCamera = 0x2E9,
    TopsTexTopTshirtsNEmbroidery = 0x2EA,
    TopsTexOnepieceOverallLNordic = 0x2EB,
    CapCostumeRacing = 0x2EC,
    SocksTexChimayo = 0x2ED,
    CapBangsReindeer = 0x2EE,
    CapHatCow = 0x2EF,
    BottomsTexSkirtBoxChidori = 0x2F0,
    BottomsTexSkirtAlineShabby = 0x2F2,
    BottomsTexPantsWidePrintdenim = 0x2F3,
    BottomsTexPantsWideSuteteko = 0x2F4,
    TopsTexOnepieceKimonoLHaregi = 0x2F5,
    CapCostumeDevil = 0x2F6,
    CapBangsSheep = 0x2F7,
    ShoesLowcutAnimal = 0x2F8,
    ShoesSandalBeachborder = 0x2F9,
    ShoesLowcutStrap = 0x2FA,
    ShoesKneeKnightIron = 0x2FB,
    ShoesLowcutSchool = 0x2FC,
    ShoesHighcutShortboots = 0x2FD,
    ShoesSandalFlower = 0x2FE,
    ShoesHighcutFurboots = 0x2FF,
    ShoesLowcutLeopard = 0x300,
    ShoesSandalBeads = 0x301,
    ShoesKneeRubberboots = 0x304,
    TopsTexOnepieceKimonoLKanpukumen = 0x305,
    TopsTexOnepieceKimonoLKanpukuwomen = 0x306,
    ShoesKneeAntique = 0x308,
    ShoesKneeKnightGold = 0x309,
    ShoesLowcutSlipper = 0x30A,
    ShoesHighcutWorkboots = 0x30B,
    ShoesHighcutMoccasin = 0x30C,
    BottomsTexSkirtLongPatch = 0x30D,
    ShoesHighcutBobbles = 0x30E,
    ShoesKneeLegguard = 0x30F,
    ShoesLowcutGlitter = 0x310,
    ShoesSandalRoomborder = 0x311,
    ShoesSandalResin = 0x312,
    ShoesHighcutSlipon = 0x313,
    TopsTexOnepieceBoxLSchoolsmock = 0x314,
    ShoesLowcutLolita = 0x315,
    CapFullfaceKingtut = 0x316,
    ShoesLowcutBallet = 0x317,
    ShoesKneeVisual = 0x318,
    TopsTexOnepieceSalopetteLRumba = 0x319,
    ShoesHighcutRubbertoe = 0x31A,
    ShoesLowcutClog = 0x31B,
    ShoesSandalComfort = 0x31C,
    ShoesSandalGladiator = 0x31D,
    ShoesKneeHero = 0x31F,
    ShoesHighcutBasket = 0x320,
    ShoesKneeClown = 0x321,
    ShoesSandalOutdoor = 0x322,
    CapHatEgg = 0x323,
    ShoesKneeWestern = 0x324,
    TopsTexOnepieceRibNChick = 0x325,
    TopsTexOnepieceAlongHRumba = 0x326,
    TopsTexTopTshirtsLSailor = 0x327,
    ShoesLowcutGgotshin = 0x328,
    ShoesSandalAqua = 0x329,
    TopsTexOnepieceOverallLHighcollar = 0x32A,
    ShoesLowcutSpike = 0x32B,
    ShoesLowcutPointedtoe = 0x32C,
    TopsTexTopYshirtsLFischerhemd = 0x32D,
    ShoesHighcutHightech = 0x32E,
    ShoesKneeSki = 0x32F,
    CapHatCavalier = 0x330,
    BottomsTexPantsHotShaggycheck = 0x331,
    BottomsTexSkirtLongEnaguas = 0x332,
    AccessoryGlassmouthCatrina = 0x333,
    ShoesKneeLaceup = 0x334,
    ShoesKneeRing = 0x335,
    CapCostumeBangs = 0x336,
    TopsTexTopOuterLPsychedelic = 0x337,
    CapCostumeHeadgear = 0x339,
    CapWigMohican = 0x33A,
    CapWigRegent = 0x33B,
    CapWigSamurai = 0x33C,
    CapWigOnionhair = 0x33D,
    CapWigWedding = 0x33E,
    CapWigDoublebun = 0x33F,
    CapBangsHeadphone = 0x340,
    CapHelmetHeaddress = 0x341,
    CapFullfaceVeil = 0x342,
    CapWigGeisya = 0x344,
    CapHelmetMusic = 0x345,
    CapFullfacePowered = 0x346,
    ShoesKneePowered = 0x347,
    BottomsTexPantsWideTeared = 0x348,
    BottomsTexPantsNormalCroppedsweat = 0x349,
    BottomsTexSkirtBoxBoxpleats = 0x34A,
    BottomsTexSkirtBoxMouton = 0x34B,
    BottomsTexPantsHotMultistripe = 0x34C,
    BottomsTexPantsNormalKnit = 0x34D,
    BottomsTexSkirtLongDenim = 0x34E,
    BottomsTexSkirtBoxApron = 0x34F,
    BottomsTexPantsHotFluffy = 0x350,
    BottomsTexPantsHalfBasketball = 0x351,
    BottomsTexPantsNormalTraining = 0x352,
    BottomsTexSkirtLongMaone = 0x353,
    BottomsTexPantsHotSequins = 0x354,
    BottomsTexPantsWideMultistripe = 0x355,
    BottomsTexPantsNormalComedian = 0x356,
    BottomsTexSkirtAlinePearl = 0x357,
    AccessoryMouthBubblegum = 0x358,
    AccessoryGlassFlower = 0x359,
    BottomsTexPantsHotLeather = 0x35C,
    BottomsTexPantsHalfGobelins = 0x35D,
    BottomsTexPantsWideThail = 0x35E,
    ShoesKneeSpace = 0x35F,
    ShoesHighcutSports = 0x360,
    AccessoryGlassmouthStraw = 0x361,
    TopsTexTopOuterNNosleeve = 0x362,
    ShoesLowcutHealth = 0x364,
    BottomsTexSkirtLongCorte = 0x366,
    BottomsTexPantsNormalChimayo = 0x367,
    TopsTexOnepieceBalloonHYumekawa = 0x368,
    TopsTexOnepieceKimonoLGaudy = 0x369,
    TopsTexOnepieceDressLNoble = 0x36A,
    TopsTexOnepieceSalopetteLPsychedelic = 0x36B,
    ShoesLowcutToilet = 0x36C,
    TopsTexOnepieceKimonoLShitamachi = 0x36D,
    ShoesHighcutCute = 0x36E,
    SocksTexFlowerdot = 0x36F,
    SocksTexArgyle = 0x370,
    ShoesLowcutMoccasin = 0x371,
    ShoesLowcutMarine = 0x372,
    ShoesLowcutWing = 0x373,
    BottomsTexSkirtLongCutleather = 0x374,
    BottomsTexSkirtAlinePatch = 0x375,
    SocksTexSeethrough = 0x376,
    SocksTexWave = 0x377,
    ShoesSandalRibbon = 0x378,
    TopsTexOnepieceBoxNTango = 0x379,
    BottomsTexSkirtLongWrapbicolor = 0x37A,
    TopsTexOnepieceBoxNFlapper = 0x37B,
    TopsTexOnepieceKimonoLKorea = 0x37C,
    TopsTexOnepieceKimonoLAsagao = 0x37D,
    ShoesSandalSports = 0x37E,
    TopsTexOnepieceOverallLSteampunk = 0x37F,
    BottomsTexSkirtLongTiedye = 0x380,
    TopsTexOnepieceOverallLFarm = 0x381,
    TopsTexOnepieceSalopetteLHockey = 0x382,
    AccessoryMouthJokeDrip = 0x383,
    CapFullfacePaperbag = 0x384,
    TopsTexTopTshirtsHStaff = 0x385,
    BottomsTexPantsHalfBotanical = 0x386,
    TopsTexTopCoatLOilskin = 0x387,
    AccessoryMouthPasta = 0x388,
    BottomsTexPantsWideGakuran = 0x389,
    BottomsTexSkirtLongLemon = 0x38A,
    BottomsTexPantsWideYumekawa = 0x38B,
    BottomsTexSkirtLongFlower = 0x38C,
    TopsTexTopYshirtsLGuide = 0x38D,
    CapHatNewyearsilk = 0x38E,
    TopsTexTopOuterLBulldog = 0x38F,
    BottomsTexSkirtLongSailor = 0x390,
    TopsTexOnepieceKimonoLHomongi = 0x391,
    TopsTexOnepieceKimonoLButterfly = 0x392,
    TopsTexOnepieceKimonoLYukatamen = 0x393,
    TopsTexTopYshirtsLDoublet = 0x394,
    CapMaskFox = 0x395,
    CapMaskOkina = 0x396,
    CapMaskNomen = 0x397,
    AccessoryGlassMirror = 0x399,
    AccessoryMouthLeather = 0x39A,
    AccessoryGlassmouthHockeyWhite = 0x39B,
    ShoesLowcutBrogues = 0x39C,
    ShoesSandalBaboush = 0x39D,
    SocksTexCountry = 0x39E,
    SocksTexStripe = 0x39F,
    SocksTexStripedot = 0x3A0,
    CapHatKanbo = 0x3A1,
    CapHatGreenery = 0x3A2,
    CapFullfaceCatcher = 0x3A3,
    CapBangsPrevention = 0x3A4,
    CapHelmetKandula = 0x3A5,
    CapFullfaceKuroko = 0x3A6,
    CapHatKnitcasquette = 0x3A7,
    CapHatScotlandRed = 0x3A8,
    AccessoryGlassMasquerade = 0x3A9,
    ShoesHighcutSneaker_ = 0x3AA,
    TopsTexTopYshirtsLGingham = 0x3AB,
    ShoesKneeEngineerboots_ = 0x3AD,
    CapOrnamentRRibbonRed_ = 0x3AE,
    TopsTexOnepieceRibNEgg = 0x3AF,
    TopsTexOnepieceRibNTuna = 0x3B0,
    TopsTexOnepieceRibNKohada = 0x3B1,
    ShoesLowcutRubbertoe = 0x3B2,
    ShoesKnee = 0x3B3,
    TopsTexTopTshirtsN = 0x3B4,
    CapOrnamentCAngel0 = 0x3B5,
    CapOrnamentTNurse = 0x3B6,
    CapHatIcecream = 0x3B7,
    CapOrnamentCBunny = 0x3B8,
    CapHatSandogasa = 0x3B9,
    CapOrnamentLMinistrawhat = 0x3BA,
    CapOrnamentLMinisilkhat = 0x3BB,
    CapMaskLeaf = 0x3BC,
    BagBackpackTown1 = 0x3BD,
    BagShoulderTravel = 0x3BE,
    CapOrnamentRose4 = 0x3BF,
    CapOrnamentRose5 = 0x3C0,
    CapOrnamentCTiara = 0x3C1,
    BagShoulderMessenger = 0x3C2,
    BagBackpackDry = 0x3C3,
    BagShoulderLeather = 0x3C4,
    BagShoulderFish = 0x3C5,
    BagShoulderFishing = 0x3C6,
    BagShoulderCage = 0x3C7,
    BagShoulderFakefur = 0x3C8,
    BagShoulderFringe = 0x3C9,
    BagShoulderRace = 0x3CA,
    BagShoulderBody = 0x3CB,
    BagShoulderBodybag = 0x3CC,
    BagShoulderDrum = 0x3CD,
    BagShoulderPattern = 0x3CE,
    BagShoulderCanvas = 0x3CF,
    BagShoulderRattan = 0x3D0,
    BagShoulderStar = 0x3D1,
    BagShoulderCherryblossoms = 0x3D2,
    BagShoulderMaple = 0x3D3,
    BagShoulderAcorn = 0x3D4,
    BagShoulderSnow = 0x3D5,
    BagShoulderShell = 0x3D6,
    BagShoulderTool = 0x3D7,
    BagShoulderSports = 0x3D8,
    BagShoulderSacosh = 0x3D9,
    BagShoulderParty = 0x3DA,
    BagBackpackWood = 0x3DB,
    BagBackpackJourney = 0x3DC,
    BagBackpackSquare = 0x3DD,
    BagBackpackOutdoor = 0x3DE,
    BagBackpackButterfly = 0x3DF,
    BagBackpackStuds = 0x3E0,
    BagBackpackSmall = 0x3E1,
    BagBackpackMountain = 0x3E2,
    BagBackpackBasket = 0x3E3,
    BagBackpackLid = 0x3E4,
    BagBackpackKnapsack = 0x3E5,
    BagBackpackTote = 0x3E6,
    BagBackpackQuilt = 0x3E7,
    BagBackpackGrass = 0x3E8,
    BagBackpackHardshell = 0x3E9,
    SocksTexStandard = 0x3EA,
    ShoesLowcutSuede = 0x3EB,
    TopsTexOnepieceAlineHOneflower = 0x3EC,
    TopsTexTopTshirtsHMvp = 0x3ED,
    TopsTexTopTshirtsHOne = 0x3EE,
    CapWigPrincess = 0x3F0,
    CapWigTurban = 0x3F1,
    CapHelmetCoin = 0x3F2,
    CapWigPigtail = 0x3F3,
    CapWigVisual = 0x3F4,
    CapOrnamentTSambaPink_ = 0x3F5,
    CapOrnamentCQueen0 = 0x3F6,
    TopsTexOnepieceAlineNMarbledot = 0x3F8,
    TopsTexOnepieceAlineNSimpledot = 0x3F9,
    TopsTexOnepieceAlineNHibiscus = 0x3FA,
    TopsTexOnepieceAlineNPolynesia = 0x3FB,
    TopsTexTopTshirtsNDanger = 0x3FD,
    TopsTexTopOuterLHeart = 0x3FE,
    TopsTexTopOuterLTree = 0x3FF,
    TopsTexTopTshirtsHFrog = 0x400,
    TopsTexTopTshirtsHBear = 0x401,
    TopsTexTopTshirtsHRabbit = 0x402,
    TopsTexTopTshirtsHStripe = 0x403,
    TopsTexTopTshirtsHLeopard = 0x404,
    TopsTexTopTshirtsHMeat = 0x405,
    TopsTexTopTshirtsHHaze = 0x406,
    TopsTexTopTshirtsHMarbledot = 0x407,
    TopsTexTopTshirtsHSimpledot = 0x408,
    TopsTexTopTshirtsLJagged = 0x409,
    TopsTexTopTshirtsHFlower = 0x40A,
    TopsTexTopYshirtsHPolynesia = 0x40B,
    TopsTexTopTshirtsHSpider = 0x40C,
    TopsTexTopTshirtsHSkull = 0x40D,
    TopsTexTopTshirtsHAce = 0x40E,
    TopsTexOnepieceAlineNPlaid = 0x40F,
    CapCostumeSnowball0 = 0x410,
    CapOrnamentLTsumamizaiku = 0x411,
    CapOrnamentLGaudy = 0x412,
    CapHatCaptainsky = 0x413,
    CapHatStudent = 0x414,
    CapOrnamentLHibiscus = 0x415,
    TopsTexTopTshirtsNStar = 0x416,
    TopsTexTopTshirtsHFire = 0x417,
    TopsTexOnepieceAlineHPlaid = 0x418,
    SocksTexNuancetights = 0x419,
    SocksTexDailytights = 0x41A,
    SocksTexVividtights = 0x41B,
    SocksTexNeontights = 0x41C,
    SocksTexVividleggings = 0x41D,
    SocksTexNeonleggings = 0x41E,
    AcceMouthTest1_ = 0x41F,
    TopsTexTopOuterLMother = 0x420,
    TopsTexTopCoatLMother = 0x421,
    TopsTexTopOuterLKnit = 0x422,
    SocksTexDailysocks = 0x423,
    SocksTexNuancesocks = 0x424,
    CapHatBaseball = 0x425,
    TopsTexTopCoatLViking = 0x426,
    TopsTexTopCoatLRaindot = 0x427,
    TopsTexOnepieceBlongLCandula = 0x428,
    CapHatTweed = 0x429,
    TopsTexTopCoatHDiner = 0x42A,
    TopsTexTopTshirtsLLayeredlogoa = 0x430,
    TopsTexTopTshirtsLLogoa = 0x432,
    TopsTexTopPuffHPlaid = 0x436,
    TopsTexTopPuffHDolly = 0x437,
    TopsTexTopCoatHWorkapron = 0x439,
    TopsTexTopTshirtsHBotanical = 0x43A,
    TopsTexTopYshirtsLPsychedelic = 0x43B,
    TopsTexOnepieceKimonoLTwelve = 0x43C,
    TopsTexOnepieceDressLMexico = 0x43D,
    TopsTexOnepieceKimonoLCrested = 0x43E,
    TopsTexOnepieceAlineNApple = 0x43F,
    TopsTexOnepieceAlineNPear = 0x440,
    TopsTexOnepieceAlineNCherry = 0x441,
    TopsTexOnepieceAlineNPeach = 0x442,
    BottomsTexPantsHalfSoccer = 0x443,
    BottomsTexPantsHalfExplorer = 0x444,
    BottomsTexSkirtBoxLStripe = 0x445,
    BottomsTexPantsNormalAmericanfootball = 0x447,
    ShoesLowcutKungfu = 0x449,
    ShoesLowcutEmbroidery = 0x44A,
    CapOrnamentLFlowerhairpin = 0x451,
    CapOrnamentLHearthairpin = 0x452,
    CapOrnamentLStarhairpin = 0x453,
    CapOrnamentFBallband = 0x454,
    CapOrnamentFFlowerband = 0x455,
    CapOrnamentFHeartband = 0x456,
    CapOrnamentTBarrette = 0x457,
    CapOrnamentTRibbon = 0x458,
    CapCostumeStar = 0x459,
    CapHatSkate = 0x45A,
    CapHatAlan = 0x45B,
    CapHatLogocap = 0x45D,
    CapHatGarlystrawhat = 0x45F,
    CapHatTulippatch = 0x461,
    CapHatApple = 0x462,
    CapHatPear = 0x463,
    CapHatCherry = 0x464,
    CapHatPeach = 0x465,
    TopsTexTopTshirtsHKate = 0x466,
    TopsTexTopCoatLKate = 0x467,
    TopsTexOnepieceAlineNKate = 0x468,
    BottomsTexPantsHalfKate = 0x469,
    BottomsTexSkirtLongKate = 0x46A,
    CapHatKatecap = 0x46B,
    CapHatKatehat = 0x46C,
    SocksTexKatetights = 0x46D,
    SocksTexKatesocks = 0x46E,
    ShoesHighcutKateboots = 0x46F,
    ShoesHighcutKatesneaker = 0x470,
    AccessoryGlassKate = 0x471,
    CapOrnamentFStarband0 = 0x473,
    TopsTexTopOuterLRco = 0x474,
    TopsTexTopTshirtsHRco = 0x475,
    CapHatMeshcapRco = 0x476,
    CapHatBandanaRco = 0x477,
    SocksTexBorderRco = 0x478,
    ShoesSandalRco = 0x479,
    TopsTexTopTshirtsHStar = 0x47A,
    CapHatRain = 0x47B,
    AccessoryGlassNook0 = 0x47C,
    TopsTexTopTshirtsHNook0 = 0x47D,
    BagBackpackNook0 = 0x47E,
    TopsTexTopYshirtsHInsect = 0x47F,
    TopsTexTopTshirtsHFish = 0x480,
    CapHatOutdoorpine = 0x481,
    TopsTexTopCoatLPajamas = 0x482,
    TopsTexOnepieceBoxLPajamas = 0x483,
    TopsTexOnepieceBalloonHVisual = 0x484,
    TopsTexOnepieceAlongLUzbek = 0x485,
    TopsTexOnepieceBlongLAttoushi = 0x486,
    TopsTexOnepieceKimonoLBingata = 0x487,
    TopsTexTopCoatLDoll = 0x488,
    TopsTexOnepieceOverallLPaint = 0x489,
    TopsTexOnepieceBoxNSamba = 0x48A,
    CapHatUzbek = 0x48B,
    CapHatMatampushi = 0x48C,
    TopsTexTopTshirtsHTwo0 = 0x48D,
    TopsTexTopTshirtsHThree0 = 0x48E,
    TopsTexTopTshirtsHFour0 = 0x48F,
    TopsTexTopTshirtsHHellojp0 = 0x490,
    TopsTexTopTshirtsHHellofr0 = 0x491,
    TopsTexTopTshirtsHHelloen0 = 0x492,
    TopsTexTopTshirtsHHellokr0 = 0x493,
    TopsTexTopTshirtsHHelloch0 = 0x494,
    TopsTexTopTshirtsHHelloge0 = 0x495,
    TopsTexTopTshirtsHHelloit0 = 0x496,
    TopsTexTopTshirtsHHellosp0 = 0x497,
    TopsTexTopTshirtsHHellors0 = 0x498,
    TopsTexTopTshirtsHHellotw0 = 0x499,
    TopsTexTopTshirtsHHelloNr0 = 0x49A,
    TopsTexTopTshirtsHDal0 = 0x49B,
    TopsTexTopCoatHDal0 = 0x49C,
    TopsTexTopOuterLDal0 = 0x49D,
    AccessoryGlassDalmask0 = 0x49E,
    AccessoryGlassDalglass0 = 0x49F,
    AccessoryGlassSlippers0 = 0x4A0,
    BagBackpackDal0 = 0x4A1,
    CapHatDal0 = 0x4A2,
    BottomsTexSkirtAlineDot = 0x4A3,
    SocksTexDotknee = 0x4A4,
    SocksTexSimpleknee = 0x4A5,
    BottomsTexSkirtBoxGrass1 = 0x4A6,
    ShoesKneeRecyclingboots0 = 0x4A7,
    CapHatOkmotors = 0x4A8,
    TopsTexTopYshirtsHOkmotors = 0x4A9,
    TopsTexTopTshirtsHOkmotors = 0x4AA,
    CapHatEggground = 0x4AB,
    CapHatEggrock = 0x4AC,
    CapHatEggleaf = 0x4AD,
    CapHatEggforest = 0x4AE,
    CapHatEggsky = 0x4AF,
    CapHatEggfish = 0x4B0,
    CapOrnamentEgg = 0x4B1,
    CapHatEggparty = 0x4B2,
    BagBackpackEgg = 0x4B3,
    TopsTexOnepieceBalloonLEgg = 0x4B4,
    TopsTexOnepieceRibNEggground = 0x4B5,
    TopsTexOnepieceRibNEggrock = 0x4B6,
    TopsTexOnepieceRibNEggleaf = 0x4B7,
    TopsTexOnepieceRibNEggforest = 0x4B8,
    TopsTexOnepieceRibNEggsky = 0x4B9,
    TopsTexOnepieceRibNEggfish = 0x4BA,
    ShoesLowcutEggground = 0x4BB,
    ShoesLowcutEggrock = 0x4BC,
    ShoesLowcutEggleaf = 0x4BD,
    ShoesLowcutEggforest = 0x4BE,
    ShoesLowcutEggsky = 0x4BF,
    ShoesLowcutEggfish = 0x4C0,
    ShoesLowcutJunepumps = 0x4C1,
    ShoesLowcutJuneshoes = 0x4C2,
    TopsTexOnepieceOverallLJune = 0x4C3,
    TopsTexTopCoatHChildren = 0x4C4,
    CapOrnamentAChildren = 0x4C5,
    CapHatSummer = 0x4C6,
    ShoesLowcutMermaid = 0x4C7,
    CapOrnamentCMermaid = 0x4C8,
    AccessoryGlassPiratespatch = 0x4C9,
    AccessoryMouthPirates = 0x4CA,
    BottomsTexPantsNormalPirates = 0x4CB,
    ShoesKneePirates = 0x4CC,
    CapHatPiratesbandana = 0x4CD,
    TopsTexOnepieceAlongLPirates = 0x4CE,
    TopsTexOnepieceOverallLPirates0 = 0x4CF,
    TopsTexTopTshirtsHTomatina = 0x4D0,
    BagBackpackHarvest = 0x4D1,
    TopsTexTopCoatHCloth = 0x4D2,
    BottomsTexPantsNormalCloth = 0x4D3,
    CapHatCloth = 0x4D4,
    BagBackpackBear = 0x4D6,
    TopsTexOnepieceAlongNMermaiddress = 0x4DC,
    TopsTexOnepieceDressNMermaid = 0x4DD,
    TopsTexTopOuterLWintersolstice = 0x4DE,
    ShoesKneeCast = 0x4DF,
    AccessoryMouthSurgicalmask = 0x4E0,
    CapHatBandage = 0x4E1,
    AccessoryMouthTissue = 0x4E3,
    SocksTexBandage = 0x4E4,
    BottomsTexPantsHotDiapers = 0x4E5,
    AccessoryGlassGauze = 0x4E6,
    CapOrnamentCPirate = 0x4E7,
    TopsTexTopYshirtsHNookyellow = 0x4E8,
    TopsTexTopYshirtsHNookgreen = 0x4E9,
    TopsTexMarinesuitNormalLNook = 0x4EA,
    TopsTexMarinesuitNormalLRashguard = 0x4EB,
    TopsTexMarinesuitNormalNGreco = 0x4EC,
    TopsTexOnepieceAlongLHalloween = 0x4ED,
    TopsTexOnepieceSalopetteLHalloween = 0x4EE,
    TopsTexOnepieceBalloonLHalloween = 0x4EF,
    TopsTexOnepieceOverallLHalloween = 0x4F0,
    CapFullfaceHalloweenhood = 0x4F1,
    CapFullfaceHalloween = 0x4F2,
    CapHatHalloween = 0x4F3,
    BagBackpackHalloween = 0x4F4,
    ShoesLowcutHalloween = 0x4F5,
    ShoesHighcutHalloween = 0x4F6,
    AccessoryMouthHalloween = 0x4F7,
    CapOrnamentFHalloween = 0x4F8,
    CapHatHalloweentriangle = 0x4F9,
    CapHatHalloweenround = 0x4FA,
    SocksTexHalloween = 0x4FB,
    CapHatKitty = 0x4FF,
    TopsTexTopTshirtsHKitty = 0x500,
    ShoesLowcutKitty = 0x501,
    CapBangsMymelody = 0x502,
    ShoesKneeMymelody = 0x503,
    CapOrnamentLKikilala = 0x504,
    TopsTexTopTshirtsHKikilala = 0x505,
    SocksTexKikilala = 0x506,
    ShoesLowcutKikilala = 0x507,
    CapWigPurin = 0x508,
    TopsTexTopTshirtsHPurin = 0x509,
    ShoesKneePurin = 0x50A,
    TopsTexTopYshirtsLCinnamoroll = 0x50B,
    ShoesLowcutCinnamoroll = 0x50C,
    TopsTexOnepieceSalopetteHKeroppi = 0x50D,
    TopsTexTopTshirtsNKeroppi = 0x50E,
    CapOrnamentCKeroppi = 0x50F,
    SocksTexKeroppi = 0x510,
    ShoesLowcutKeroppi = 0x511,
    TopsTexTopYshirtsHUniform = 0x512,
    AccessoryGlassmouthNook = 0x514,
    TopsTexOnepieceKimonoLWeaverwomen = 0x515,
    TopsTexOnepieceKimonoLWeavermen = 0x516,
    TopsTexOnepieceAlineLKitty = 0x517,
    CapBangsCinnamoroll = 0x518,
    TopsTexTopPuffHCinnamoroll = 0x519,
    AccessoryGlassSummer = 0x51F,
    CapBangsWinter = 0x520,
    TopsTexOnepieceRobeLHalloween = 0x523,
    TopsTexOnepieceAlineHKikilala = 0x524,
    TopsTexOnepieceAlineLPurin = 0x525,
    CapHatMario = 0x526,
    CapHatLuigi = 0x527,
    CapHatWario = 0x528,
    TopsTexOnepieceSalopetteLMario = 0x529,
    TopsTexOnepieceSalopetteLLuigi = 0x52A,
    TopsTexOnepieceOverallHWario = 0x52B,
    AccessoryGlassmouthMario = 0x52C,
    AccessoryGlassmouthLuigi = 0x52D,
    AccessoryGlassmouthWario = 0x52E,
    ShoesLowcutWario = 0x52F,
    ShoesLowcutMario = 0x530,
    CapOrnamentAPeach = 0x531,
    TopsTexOnepieceDressHPeach = 0x532,
    ShoesLowcutPeach = 0x533,
    TopsTexOnepieceBalloonHMymelody = 0x534,
    TopsTexTopYshirtsHMymelody = 0x535,
    TopsTexOnepieceAlineHUniform = 0x539,
    CapOrnamentLPlumeria = 0x53E,
    CapMaskOkame = 0x53F,
    TopsTexOnepieceSalopetteLCarnival = 0x540,
    CapOrnamentCVine = 0x542,
    CapOrnamentFMoss = 0x543,
    CapCostumeMoss = 0x544,
    CapHatMoss = 0x545,
    CapHatVine = 0x546,
    CapHatShamrock0 = 0x547,
    TopsTexOnepieceSalopetteLShamrock0 = 0x548,
    ShoesLowcutShamrock0 = 0x549,
    AccessoryGlassShamrock0 = 0x54A,
    ShoesLowcutLuigi = 0x54B,
    AccessoryMouthTissuedouble = 0x54C,
    TopsTexOnepieceOverallNVine = 0x54D,
    BagShoulderVine = 0x54E,
    TopsTexOnepieceSalopetteemmLMoss = 0x54F,
    TopsTexOnepieceBalloonemmHMoss = 0x550,
    TopsTexOnepieceOverallLColorsuits = 0x551,
    BagShoulderTasukiprom = 0x552,
    ShoesLowcutDanceshoes = 0x553,
    CapOrnamentCCrownprom = 0x554,
    CapOrnamentCTiaraprom = 0x555,
    TopsTexTopCoatLWhitecoatDirty = 0x556,
    TopsTexTopYshirtsHSchoolshirts = 0x557,
    TopsTexTopTshirtsLSchoolsailor = 0x558,
    AccessoryGlassWellington = 0x559,
    TopsTexTopCoatLSchoollunch = 0x55A,
    CapHatSchoollunch = 0x55B,
    TopsTexTopYshirtsLJacketteacher = 0x55C,
    TopsTexTopYshirtsLJacketpattern = 0x55D,
    CapWigTsunokakushi = 0x55E,
    CapHatPhrygian = 0x55F,
    TopsTexOnepieceKimonoLCrestedWhite = 0x560,
    TopsTexOnepieceKimonoLPurewhite = 0x561,
    TopsTexTopCoatLFather = 0x562,
    CapHatCrewcap = 0x563,
    CapHatHuntingsimple = 0x564,
    CapHatTrianglesimple = 0x565,
    TopsTexTopYshirtsHMarket = 0x566,
    CapHatMarket = 0x567,
    CapHatCocklogo = 0x568,
    TopsTexTopCoatLCook = 0x569,
    TopsTexOnepieceDressLMaid = 0x56A,
    CapOrnamentCTwistedheadband = 0x56B,
    TopsTexTopYshirtsLUniformgilet = 0x56C,
    TopsTexTopCoatHHawaiianapron = 0x56D,
    TopsTexTopYshirtsLSeniorvest = 0x56E,
    AccessoryGlassThurmontsquare = 0x56F,
    TopsTexTopYshirtsLOpenjersey = 0x570,
    TopsTexTopYshirtsHTowel = 0x571,
    TopsTexTopCoatLWindbreaker = 0x572,
    BagBackpackRandsel = 0x573,
    BagBackpackSchoolbag = 0x574,
    BottomsTexSkirtLongRubber = 0x575,
    TopsTexTopYshirtsLLayeredpolo = 0x576,
    TopsTexOnepieceOverallLHygiene = 0x577,
    CapCostumeHygiene = 0x578,
    TopsTexTopCoatLJapanesestyle = 0x579,
    TopsTexOnepieceSalopetteHUniform = 0x57E,
    SocksTexProtector = 0x57F,
    TopsTexTopOuterLCardiganribbon = 0x580,
    TopsTexTopCoatLDelivery = 0x581,
    BagBackpackDelivery = 0x582,
    TopsTexTopTshirtsHBib = 0x583,
    TopsTexTopTshirtsHKanjipassion = 0x586,
    TopsTexTopOuterLTakumijacket = 0x587,
    TopsTexTopYshirtsLTakumisuit = 0x588,
    TopsTexTopTshirtsHTakumi = 0x589,
    TopsTexTopTshirtsNTakumitanktop = 0x58A,
    ShoesSandalTakumi = 0x58B,
    ShoesLowcutTakumislipper = 0x58C,
    CapOrnamentAKankanbo = 0x58D,
    CapOrnamentAParty = 0x58E,
    TopsTexOnepieceOverallHAerobics = 0x58F,
    TopsTexTopOuterLNook = 0x590,
    BagShoulderNook = 0x591,
    TopsTexTopYshirtsLBlazerribbon = 0x592,
    TopsTexTopYshirtsLBlazerknit = 0x593,
    BottomsTexSkirtAlineStudent = 0x594,
    BottomsTexPantsWideStudent = 0x595,
    CapOrnamentCOrnament = 0x596,
    BottomsTexPantsNormalSlackspattern = 0x597,
    BottomsTexPantsWideSlacksteacher = 0x598,
    TopsTexTopTshirtsemmLDjkk = 0x599,
    TopsTexTopTshirtsemmNTakumi = 0x59A,
    TopsTexTopTshirtsemmNLayered = 0x59B,
    CapOrnamentCLuminouscorolla = 0x59C,
    CapHatLuminousbandana = 0x59D,
    AccessoryGlassNeon = 0x59E,
    CapWigRibbon = 0x59F,
    CapWigPank = 0x5A0,
    TopsTexTopCoatH = 0x5A2,
    TopsTexTopTshirtsNPendant = 0x5A3,
    TopsTexTopCoatLCafecool = 0x5A5,
    TopsTexOnepieceAlineHCafecute = 0x5A6,
    AccessoryGlassmouthVenezia = 0x5A7,
    TopsTexOnepieceBlongLMoroccan = 0x5A8,
    CapHatSteampunk = 0x5A9,
    CapOrnamentAAntenna = 0x5AA,
    CapFullfaceBoss = 0x5AB,
    TopsTexOnepieceKimonoLSamurai = 0x5AC,
    ShoesLowcutNomalpumps = 0x5AD,
    BottomsTexSkirtBoxTeacher = 0x5AE,
    BagBackpackTownPattern = 0x5AF,
    BagShoulderGamaguchi = 0x5B0,
    BagBackpackMusician = 0x5B1,
    BagShoulderSword = 0x5B2,
    CapHatSafetyhatlight = 0x5B3,
    TopsTexTopTshirtsNTanktopdirty = 0x5B4,
    AccessoryGlassNomal = 0x5B5,
    CapHatTrain = 0x5B6,
    TopsTexTopCoatLTrain = 0x5B8,
    TopsTexTopTshirtsHRoomwear = 0x5B9,
    BottomsTexPantsHalfRoomwear = 0x5BA,
    TopsTexOnepieceAlongHTakumi = 0x5BB,
    TopsTexTopYshirtsHTakumi = 0x5BC,
    BagShoulderSquare = 0x5BD,
    BagBackpackJet = 0x5BE,
    BagBackpackStudent = 0x5BF,
    BagShoulderYumekawa = 0x5C0,
    BagBackpackPanda = 0x5C1,
    TopsTexOnepieceRibLTakumi = 0x5C3,
    TopsTexOnepieceBoxNTakumi = 0x5C4,
    BagBackpackTownLeopard = 0x5C5,
    BagBackpackTownZebra = 0x5C6,
    BagBackpackTownSimple = 0x5C7,
    BagBackpackTownCheck = 0x5C8,
    BagBackpackTownDot = 0x5C9,
    BagBackpackTownSpace = 0x5CA,
    BagBackpackTownYumekawa = 0x5CB,
    TopsTexOnepieceOverallLHaramaki = 0x5CD,
    TopsTexTopCoatHGoyokiki = 0x5CE,
    CapHatAuctioncap = 0x5CF,
    TopsTexTopTshirtsHHerorobot = 0x5D0,
    AccessoryGlassSolideyes = 0x5D1,
    BagShoulderGamaguchiAsian = 0x5D2,
    BagShoulderGamaguchiJapan = 0x5D3,
    BagShoulderGamaguchiBijou = 0x5D4,
    BagShoulderYumekawaRibbon = 0x5D5,
    BagShoulderYumekawaUnicorn = 0x5D6,
    TopsTexOnepieceRibLDark = 0x5D7,
    TopsTexTopCoatLBattle = 0x5D8,
    TopsTexOnepieceBalloonHSteampunk = 0x5D9,
    BagShoulderSquarePython = 0x5DA,
    BagShoulderSquareZebra = 0x5DB,
    ToolBagBasket = 0x5DF,
    ToolBagBasketborder = 0x5E0,
    ToolBagBasketdiagram = 0x5E1,
    ToolBagFuroshiki = 0x5E2,
    ToolBagLeather = 0x5E3,
    ToolBagPaper = 0x5E4,
    ToolBagPaperelectric = 0x5E5,
    ToolBagPaperfashion = 0x5E6,
    ToolBagPaperflower = 0x5E7,
    ToolBagSecond = 0x5E8,
    ToolBagTote = 0x5E9,
    ToolBagTotecamouflage = 0x5EA,
    ToolBagToteflower = 0x5EB,
    ToolBagTotelogo = 0x5EC,
    ToolBagEco = 0x5ED,
    ToolBagEcofish = 0x5EE,
    ToolBagEcobread = 0x5EF,
    ToolBagEcoflower = 0x5F0,
    ShoesLowcutBeans = 0x5F4,
    ShoesLowcutBeansCyan = 0x5F6,
    TopsTexTopOuterLIkasweat = 0x5F7,
    TopsTexTopCoatLLink = 0x5F8,
    CapWigLink = 0x5F9,
    CapWigZelda = 0x5FA,
    ShoesSandalZelda = 0x5FB,
    TopsTexOnepieceBlongNZelda = 0x5FC,
    CapWigChampion = 0x5FD,
    TopsTexTopCoatLChampion = 0x5FE,
    ShoesKneeHylia = 0x5FF,
    BottomsTexPantsNormalHylia = 0x600,
    TopsTexOnepieceAlineLMineru = 0x601,
    CapWigInkling = 0x602,
    CapWigOctling = 0x603,
    TopsTexTopTshirtsHFuka = 0x604,
    TopsTexTopTshirtsHUtsuho = 0x605,
    TopsTexTopCoatNTulin = 0x606,
    TopsTexTopCoatLReplica = 0x607,
    ShoesKneeReplica = 0x608,
    CapOrnamentSalmonBaby = 0x609,
    BottomsTexPantsNormalInkling = 0x60A,
    TopsTexTopTshirtsHTrishred = 0x60B,
    ShoesKneeForcereBoots = 0x60C,
    TopsTexTopOuterLTakoroka = 0x60D,
    BagBackpackInktank = 0x60E,
    CapMaskMajora = 0x60F,
    CapOrnamentTri = 0x611,
    BagBackpackMasterswordHylianshield = 0x612,
    TopsTexTopTshirtsHLegoLogo = 0x615,
    TopsTexTopTshirtsHLegoHead = 0x616,
    TopsTexTopTshirtsHHotel = 0x61C,
    TopsTexTopTshirtsHLegoblock = 0x61E,
    TopsTexTopYshirtsHHotelB = 0x61F,
    TopsTexTopOuterLHotelB = 0x620,
    TopsTexTopYshirtsHHotel = 0x621,
    TopsTexTopOuterLHotel = 0x622,
    TopsTexTopTshirtsHHotelB = 0x623,
    CapHatTriangleHotel = 0x624,
    TopsTexTopTshirtsLBorder = 0x06,
    TopsTexTopYshirtsLMountain = 0x08,
    TopsTexTopCoatLDuffle = 0x0D,
    TopsTexOnepieceRibLKnit = 0x09,
    TopsTexOnepieceRibLParka = 0x0A,
    TopsTexOnepieceBoxHJumperskirt = 0x0B,
    TopsTexOnepieceBoxHLayercamisole = 0x0C,
    BottomsTexPantsNormalChino = 0x0E,
    BottomsTexPantsNormalTwotone = 0x0F,
    BottomsTexSkirtAlineGingham = 0x10,
    BottomsTexPantsNormalDenimNonwa = 0x11,

    Unknown = ushort.MaxValue,
}

public static class ItemClothGroupExtensions
{
    private static readonly HashSet<ItemClothGroup> SortedByColorGroup = [
        TopsTexTopOuterLDownjacketBlue,
        TopsTexTopTshirtsHSailor,
        TopsTexOnepieceBalloonHHoodRed,
        TopsTexOnepieceAlineLHeroine,
        TopsTexOnepieceAlineNXmastreeNormal,
        TopsTexTopYshirtsLDenim,
        TopsTexTopTshirtsHFishing,
        TopsTexTopYshirtsNDenim,
        TopsTexTopOuterLJersey,
        TopsTexTopTshirtsHCamouflage,
        BottomsTexPantsNormalJersey,
        BottomsTexPantsNormalDenimholes,
        BottomsTexSkirtAlineSailorNavy,
        BottomsTexPantsNormalCamouflage,
        TopsTexOnepieceOverallLBear,
        TopsTexOnepieceOverallLFrog,
        TopsTexOnepieceOverallLKappa,
        TopsTexOnepieceOverallLHero,
        TopsTexOnepieceOverallLNinja,
        TopsTexOnepieceAlongLWitch,
        TopsTexTopTshirtsHKanji,
        TopsTexTopYshirtsLFleece,
        BottomsTexSkirtBoxDenim,
        BottomsTexPantsHotDenimholes,
        BottomsTexPantsNormalDown,
        BottomsTexSkirtBoxDown,
        BottomsTexPantsHotDenim,
        BottomsTexPantsWideDenim,
        TopsTexOnepieceBalloonHMagical,
        TopsTexTopYshirtsLGakuran,
        TopsTexTopYshirtsLGakuranopen,
        TopsTexTopOuterLCamo,
        BottomsTexSkirtBoxCamo,
        BottomsTexPantsHalfOutdoor,
        BottomsTexPantsHalfJersey,
        TopsTexOnepieceRibNCaterpillar,
        TopsTexOnepieceOverallLDevil,
        SocksTexDenimleggings,
        SocksTexNordic,
        SocksTexMultiblock,
        CapHatWitch,
        CapHatDenim,
        CapHatNightcap,
        CapHatCowl,
        CapHatBear,
        CapHatKappa,
        CapCostumeFrog,
        TopsTexOnepieceOverallLMuscle,
        CapCostumeNinja,
        CapBangsEarknit,
        CapHelmetHero,
        BottomsTexPantsWidePrintdenim,
        CapCostumeDevil,
        BottomsTexSkirtLongDenim,
        BottomsTexPantsWideGakuran,
        BottomsTexSkirtLongSailor,
        CapBangsPrevention,
        TopsTexTopTshirtsN,
        CapOrnamentLTsumamizaiku,
        CapHatStudent,
        SocksTexNuancetights,
        SocksTexNuancesocks,
        TopsTexOnepieceDressLMexico,
        BottomsTexPantsHalfSoccer,
        TopsTexTopCoatLPajamas,
        BagBackpackBear,
        AccessoryMouthSurgicalmask,
        BottomsTexPantsHotDiapers,
        TopsTexTopCoatLWhitecoatDirty,
        TopsTexTopYshirtsHSchoolshirts,
        TopsTexTopTshirtsLSchoolsailor,
        TopsTexTopYshirtsLJacketteacher,
        TopsTexTopYshirtsLJacketpattern,
        CapHatCrewcap,
        TopsTexTopYshirtsHMarket,
        CapHatMarket,
        CapHatCocklogo,
        TopsTexTopCoatLCook,
        TopsTexOnepieceDressLMaid,
        CapOrnamentCTwistedheadband,
        TopsTexTopYshirtsLUniformgilet,
        TopsTexTopCoatHHawaiianapron,
        TopsTexTopYshirtsLOpenjersey,
        TopsTexTopYshirtsHTowel,
        TopsTexTopCoatLWindbreaker,
        BagBackpackRandsel,
        BagBackpackSchoolbag,
        BottomsTexSkirtLongRubber,
        TopsTexTopYshirtsLLayeredpolo,
        TopsTexTopCoatLJapanesestyle,
        TopsTexOnepieceSalopetteHUniform,
        SocksTexProtector,
        TopsTexTopCoatLDelivery,
        BagBackpackDelivery,
        TopsTexTopTshirtsHKanjipassion,
        CapOrnamentAParty,
        TopsTexTopYshirtsLBlazerribbon,
        TopsTexTopYshirtsLBlazerknit,
        BottomsTexSkirtAlineStudent,
        BottomsTexPantsWideStudent,
        BottomsTexPantsNormalSlackspattern,
        BottomsTexPantsWideSlacksteacher,
        TopsTexTopTshirtsemmLDjkk,
        TopsTexTopTshirtsemmNTakumi,
        TopsTexTopTshirtsemmNLayered,
        CapOrnamentCLuminouscorolla,
        CapHatLuminousbandana,
        AccessoryGlassNeon,
        CapWigRibbon,
        TopsTexTopCoatH,
        TopsTexTopCoatLCafecool,
        TopsTexOnepieceAlineHCafecute,
        AccessoryGlassmouthVenezia,
        TopsTexOnepieceBlongLMoroccan,
        CapHatSteampunk,
        CapOrnamentAAntenna,
        CapFullfaceBoss,
        ShoesLowcutNomalpumps,
        BottomsTexSkirtBoxTeacher,
        BagBackpackTownPattern,
        BagBackpackMusician,
        BagShoulderSword,
        AccessoryGlassNomal,
        CapHatTrain,
        TopsTexTopCoatLTrain,
        TopsTexTopTshirtsHRoomwear,
        BottomsTexPantsHalfRoomwear,
        BagShoulderSquare,
        BagBackpackJet,
        BagBackpackPanda,
        BagBackpackTownLeopard,
        BagBackpackTownZebra,
        BagBackpackTownSimple,
        BagBackpackTownYumekawa,
        TopsTexTopCoatHGoyokiki,
        CapHatAuctioncap,
        TopsTexTopTshirtsHHerorobot,
        AccessoryGlassSolideyes,
        BagShoulderGamaguchiAsian,
        BagShoulderGamaguchiJapan,
        BagShoulderGamaguchiBijou,
        TopsTexOnepieceRibLDark,
        TopsTexTopCoatLBattle,
        TopsTexOnepieceBalloonHSteampunk,
        BagShoulderSquarePython,
        BagShoulderSquareZebra,
        ToolBagBasket,
        ToolBagBasketborder,
        ToolBagFuroshiki,
        ToolBagLeather,
        ToolBagPaper,
        ToolBagPaperelectric,
        ToolBagPaperflower,
        ToolBagSecond,
        TopsTexOnepieceBoxHJumperskirt,
        BottomsTexPantsNormalChino,
        BottomsTexPantsNormalDenimNonwa,
    ];

    extension(ItemClothGroup g)
    {
        public bool UsesColorGroupSort => SortedByColorGroup.Contains(g);
    }
}
