//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSE.Parsing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHSE.Parsing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from bcsv import *
        ///
        ///enum_009fa2d460ce_286d6aa2ee6b = (
        ///	(&apos;EC&apos;, &apos;東進入禁止&apos;),
        ///	(&apos;WC&apos;, &apos;西進入禁止&apos;),
        ///	(&apos;3B&apos;, &apos;東西進入可&apos;),
        ///)
        ///
        ///enum_01016811d685_37fe72043e75 = (
        ///	(&apos;KeepSwimming&apos;  , &apos;回遊：通常&apos;),
        ///	(&apos;Float&apos;         , &apos;待機&apos;),
        ///	(&apos;RoundsSwimming&apos;, &apos;回遊：見回り&apos;),
        ///	(&apos;ChasePlayer&apos;   , &apos;プレイヤーサーチ&apos;),
        ///	(&apos;Legion&apos;        , &apos;大群&apos;),
        ///	(&apos;Predator&apos;      , &apos;捕食者&apos;),
        ///	(&apos;AntiStream&apos;    , &apos;抗水流&apos;),
        ///	(&apos;SwimAndWait&apos;   , &apos;回遊＆待機&apos;),
        ///)
        ///
        ///enum_017c76af34f4_35ed35a1a2a5 = (
        ///	(&apos;Light&apos;     , &apos;軽い&apos;),
        ///	(&apos;Normal&apos;    , &apos;通常&apos;),
        ///	(&apos;Heavy&apos;     , &apos;重い&apos;),
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string specs_120 {
            get {
                return ResourceManager.GetString("specs_120", resourceCulture);
            }
        }
    }
}
