//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSE.Parsing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHSE.Parsing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from bcsv import *
        ///
        ///enum_8c2aec6a = (
        ///	(&apos;Before&apos;, &apos;前日&apos;),
        ///	(&apos;Skip&apos;  , &apos;中止&apos;),
        ///	(&apos;Same&apos;  , &apos;同時開催&apos;),
        ///)
        ///
        ///enum_GroundedItemType = (
        ///	(&apos;All&apos;            , &apos;全部&apos;),
        ///	(&apos;TreeOak&apos;        , &apos;植物：木：広葉樹&apos;),
        ///	(&apos;TreeOakStump&apos;   , &apos;植物：木：広葉樹：切り株&apos;),
        ///	(&apos;TreeCedar&apos;      , &apos;植物：木：針葉樹&apos;),
        ///	(&apos;TreeCedarStump&apos; , &apos;植物：木：針葉樹：切り株&apos;),
        ///	(&apos;TreePalm&apos;       , &apos;植物：木：ヤシの木&apos;),
        ///	(&apos;TreePalmStump&apos;  , &apos;植物：木：ヤシの木：切り株&apos;),
        ///	(&apos;TreeBamboo&apos;     , &apos;植物：木：竹&apos;),
        ///	(&apos;TreeBambooStump&apos;, &apos;植物：木：竹：切り株&apos;),
        ///	(&apos;TreeFruit&apos;      , &apos;植物：木：果物&apos;),
        ///	(&apos;TreeEasterEgg&apos;  , [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string specs_111 {
            get {
                return ResourceManager.GetString("specs_111", resourceCulture);
            }
        }
    }
}
